<div class="container"> <br>
    <div class="row">
        <div class="col-md-4 col-sm-4 text-center">
            <img src="<?= $this->basePath('img/areaRestringida.png'); ?>" class="rounded img-fluid" alt="Imagen" style="width: 70%; height: auto">
        </div>
        <div class="col-md-8 col-sm-8"> <br><br>
            <div class="alert alert-danger text-center text-monospace" role="alert">
                <p class="font-weight-bold">
                    SU SESI&Oacute;N HA TERMINADO
                </p>
                <i class="fas fa-exclamation-triangle fa-lg"></i> &nbsp; 
                <i class="fas fa-exclamation-triangle fa-lg"></i> &nbsp; 
                <i class="fas fa-exclamation-triangle fa-lg"></i>
            </div>
            <div class="col-md-12 col-sm-12">
                <div class="alert alert-primary text-center" role="alert">
                    <p>Por favor actualice la p&aacute;gina e inicie sesi&oacute;n nuevamente </p>
                    <button type="button" onclick="location.reload(true)" class="btn btn-sm btn-primary">Iniciar Sesi&oacute;n</button>
                </div>
            </div>
        </div>
    </div> <hr>
</div>