<?php
$form->prepare();
echo $this->form()->openTag($form);
?>
<div class="modal-body ui-front">
    <div style="padding: 10px" class="container-fluid text-center">        
        <fieldset>
            <legend>Informacion del Rol</legend>
            <hr>
            <div class="form-row">               
                <div class="form-group col-md-3 col-sm-12 text-right">
                    <?= $this->formLabel($form->get('rol')) ?>
                </div>                
                <div class="form-group col-md-6 col-sm-12">                    
                    <div class="input-group">
                        <?= $this->formElement($form->get('rol')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fa fa-user-plus"></i>
                            </span>
                        </div>
                    </div>
                </div>                
            </div>            
        </fieldset>                    
    </div>
</div>
<div class="modal-footer" id="footerFormularioReg" style=" padding: 20px">    
    <button type="button" class="btn btn-danger" data-dismiss="modal"><i class="fas fa-times"></i> Cerrar</button>
</div>
<?= $this->form()->closeTag(); ?>