<?php
$form->prepare();
echo $this->form()->openTag($form);
?>
<div class="modal-body" id="formularioReg">
    <div style="padding: 10px" class="container-fluid text-center">        
        <fieldset>
            <fieldset>
                <legend>Informacion del Rol</legend>
                <hr>
                <div class="form-row">               
                    <div class="form-group col-md-3 col-sm-12 text-right">
                        <?= $this->formLabel($form->get('rol')) ?>
                    </div>                
                    <div class="form-group col-md-6 col-sm-12">                    
                        <div class="input-group">
                            <?= $this->formElement($form->get('rol')) ?>
                            <div class="input-group-append">
                                <span class="input-group-text">
                                    <i class="fa fa-user-plus"></i>
                                </span>
                            </div>
                        </div>
                    </div>                
                </div>
            </fieldset>            
        </fieldset><hr>
        <fieldset>
            <legend>Informacion de Registro</legend>
            <hr>            
            <div class="form-row">
                <div class="form-group col-md-5 col-sm-12 text-right">
                    <?= $this->formLabel($form->get('idRol')) ?>
                </div>
                <div class="form-group col-md-3 col-sm-12">
                    <div class="input-group">
                        <?= $this->formElement($form->get('idRol')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-user"></i>
                            </span>
                        </div>
                    </div>
                </div>
            </div>                
        </fieldset>        
    </div>
</div>
<div class="modal-footer" style=" padding: 20px">
    <button type="submit" class="btn btn-success" title="ACTUALIZAR ROL"><i class="fas fa-save"></i> Actualizar Rol</button>
    <button type="button" class="btn btn-danger" data-dismiss="modal"><i class="fas fa-times"></i> Cerrar</button>
</div>
<?= $this->form()->closeTag(); ?>