<?php
$this->formUsuario->prepare();
echo $this->form()->openTag($this->formUsuario);
?>
<div class="modal-body ui-front" style="max-height: 450px; overflow-y: auto;">
    <div class="container-fluid">
        <fieldset>
            <legend>Busqueda del Usuario</legend>
            <hr>
            <div class="form-row">
                <div class="form-group col-md-6 col-sm-6">
                    <label for="identificacionBusqAux">Identificacion</label>
                    <div class="input-group">
                        <input type="number" id="identificacionBusqAux" name="identificacionBusqAux" value=""
                            class="form-control">
                        <div class="input-group-append">
                            <button type="button" id="btnBuscarByIdentificacion" onclick="buscarByIdentificacion()"
                                class="btn btn-primary">
                                <i class="fas fa-search"></i>
                            </button>
                        </div>
                    </div>
                </div>
            </div>
            <div class="alert alert-warning" role="alert">
                Busqueda de funcionario: Si el funcioanrio no se encuentra en la busqueda por favor re
            </div>
        </fieldset>
        <hr>
        <div id="divInfoCliente"></div>
        <fieldset>
            <!-- <div class="form-row">
                <div class="form-group col-md-6 col-sm-6">
                    <?= $this->formLabel($this->formUsuario->get('idRol')) ?>
                    <div class="input-group">
                        <?= $this->formElement($this->formUsuario->get('idRol')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-users"></i>
                            </span>
                        </div>
                    </div>
                </div>
            </div> -->
        </fieldset>
        <!-- <div class="alert alert-primary" role="alert">
            <p class="font-weight-bold">
                <i class="fas fa-info-circle"></i>
                Cuando se registre un nuevo usuario se generará un usuario y contraseña predeterminado.
            </p>
            <p class="font-weight-bold">Ejemplo:</p>
            Usuario: jpepito | Contraseña: jpepito*2026
        </div> -->
    </div>
</div>
<div class="modal-footer">
    <button type="submit" class="btn btn-success" title="Registrar Usuario"><i class="fas fa-save"></i> Registrar
        Usuario</button>
    <button type="button" class="btn btn-danger" data-dismiss="modal"><i class="far fa-times-circle"></i>
        Cerrar</button>
</div>
<?= $this->form()->closeTag(); ?>