<?php
$this->formUsuario->prepare();
echo $this->form()->openTag($this->formUsuario);
?>
<div class="modal-body ui-front" style="max-height: 450px; overflow-y: auto;">
    <div class="container-fluid">
        <fieldset>
            <legend>Informacion del Usuario</legend> <hr>
            <div class="form-row">
                <div class="form-group col-md-2 col-sm-2">
                    <?= $this->formLabel($this->formUsuario->get('idUsuario')) ?>
                    <div class="input-group input-group-sm" >  
                        <?= $this->formElement($this->formUsuario->get('idUsuario')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-key"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-5 col-sm-5">
                    <?= $this->formLabel($this->formUsuario->get('empleado')) ?>
                    <div  class="input-group input-group-sm">
                        <?= $this->formElement($this->formUsuario->get('empleado')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-user"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-5 col-sm-5">
                    <?= $this->formLabel($this->formUsuario->get('login')) ?>
                    <div  class="input-group input-group-sm">
                        <?= $this->formElement($this->formUsuario->get('login')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-user"></i>
                            </span>
                        </div>
                    </div>
                </div>
            </div>

        </fieldset> <hr>  
        <fieldset>
            <legend>Informacion de los Roles Asociados </legend> <hr>
            <div class="row border rounded-lg shadow-sm p-3">
                <div class="table-responsive" style="font-size: 11px">
                    <table id="tblUsuarioRoles" class="table table-striped table-bordered table-hover nowrap table-sm" >
                        <thead class="thead-dark">
                            <tr>
                                <th scope="col" class="text-center align-middle" style="width: 3%">ID</th>
                                <th scope="col" class="text-center align-middle">ROL</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php
                            foreach ($this->infoRoles as $rol) {
                                echo '<tr>';
                                echo '<th class="text-center align-middle">' . $rol['idRol'] . '</th>';
                                echo '<td class="text-center align-middle">' . $rol['rol'] . '</td>';
                                echo '</tr>';
                            }
                            ?>
                        </tbody>
                        <tfoot></tfoot>
                    </table>
                </div>
            </div>
        </fieldset>
        <fieldset>
            <legend>Cambio de Contraseña</legend> <hr>
            <div class="form-row">
                <div class="form-group col-md-6 col-sm-6">
                    <?= $this->formLabel($this->formUsuario->get('nueva_contrasena')) ?>
                    <div class="input-group input-group-sm">
                        <?= $this->formElement($this->formUsuario->get('nueva_contrasena')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text" style="cursor: pointer;" onclick="togglePasswordNueva('nueva_contrasena', this)">
                                <i class="fas fa-eye"></i>
                            </span>
                            <span class="input-group-text">
                                <i class="fas fa-lock"></i>
                            </span>

                        </div>
                    </div>
                    <div class="progress mt-2" style="height: 6px;">
                        <div id="password-strength-bar" class="progress-bar" role="progressbar" style="width: 0%"></div>
                    </div>
                    <small id="password-strength-text" class="form-text text-muted"></small>
                </div>
                <div class="form-group col-md-6 col-sm-6">
                    <?= $this->formLabel($this->formUsuario->get('confirmar_contrasena')) ?>
                    <div class="input-group input-group-sm">
                        <?= $this->formElement($this->formUsuario->get('confirmar_contrasena')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text" style="cursor: pointer;" onclick="togglePasswordConfirmacion('confirmar_contrasena', this)">
                                <i class="fas fa-eye"></i>
                            </span>
                            <span class="input-group-text">
                                <i class="fas fa-lock"></i>
                            </span>
                        </div>
                    </div>
                    <small id="password-strength-text" class="form-text text-muted"></small>
                </div>
            </div>
        </fieldset> <hr>
        <fieldset> 
            <legend>Informacion de Registro</legend> <hr>
            <div class="form-row">
                <div class="form-group col-md-3 col-sm-3">
                    <label for="idEmpleado">ID Empleado</label>
                    <div class="input-group input-group-sm">
                        <input type="text" id="idEmpleado" name="idEmpleado" value="<?= $this->infoUsuario['idEmpleado'] ?>" class="form-control font-weight-bold" readonly>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-key"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-4 col-sm-4">
                    <?= $this->formLabel($this->formUsuario->get('estado')) ?>
                    <div  class="input-group input-group-sm">
                        <?= $this->formElement($this->formUsuario->get('estado')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="far fa-clock"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-2 col-sm-2">
                    <?= $this->formLabel($this->formUsuario->get('contFallidos')) ?>
                    <div  class="input-group input-group-sm">
                        <?= $this->formElement($this->formUsuario->get('contFallidos')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-exclamation-circle"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-3 col-sm-3">
                    <?= $this->formLabel($this->formUsuario->get('idUsuario')) ?>
                    <div class="input-group input-group-sm" >  
                        <?= $this->formElement($this->formUsuario->get('idUsuario')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-key"></i>
                            </span>
                        </div>
                    </div>
                </div>
                
                <div class="form-group col-md-6 col-sm-6">
                    <?= $this->formLabel($this->formUsuario->get('registradopor')) ?>
                    <div  class="input-group input-group-sm">
                        <?= $this->formElement($this->formUsuario->get('registradopor')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="far fa-clock"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-6 col-sm-6">
                    <?= $this->formLabel($this->formUsuario->get('fechahorareg')) ?>
                    <div  class="input-group input-group-sm">
                        <?= $this->formElement($this->formUsuario->get('fechahorareg')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="far fa-clock"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-6 col-sm-6">
                    <?= $this->formLabel($this->formUsuario->get('fechaultfallido')) ?>
                    <div  class="input-group input-group-sm">
                        <?= $this->formElement($this->formUsuario->get('fechaultfallido')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="far fa-clock"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-6 col-sm-6">
                    <?= $this->formLabel($this->formUsuario->get('fechaultingreso')) ?>
                    <div  class="input-group input-group-sm">
                        <?= $this->formElement($this->formUsuario->get('fechaultingreso')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="far fa-clock"></i>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </fieldset>
    </div>
</div>
<div class="modal-footer">
    <button type="submit" class="btn btn-success" title="Cambiar Contraseña"><i class="fas fa-save"></i> Cambiar Contraseña</button>
    <button type="button" class="btn btn-danger" data-dismiss="modal"><i class="far fa-times-circle"></i> Cerrar</button>
</div>
<?= $this->form()->closeTag(); ?>