<?php
$this->formUsuario->prepare();
echo $this->form()->openTag($this->formUsuario);
?>
<div class="modal-body ui-front" style="max-height: 450px; overflow-y: auto;">
    <div class="container-fluid">
        <fieldset>
            <legend>Informacion del Usuario</legend> <hr>
            <div class="form-row">
                <div class="form-group col-md-2 col-sm-2">
                    <?= $this->formLabel($this->formUsuario->get('idUsuario')) ?>
                    <div class="input-group input-group-sm" >  
                        <?= $this->formElement($this->formUsuario->get('idUsuario')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-key"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-5 col-sm-5">
                    <?= $this->formLabel($this->formUsuario->get('empleado')) ?>
                    <div  class="input-group input-group-sm">
                        <?= $this->formElement($this->formUsuario->get('empleado')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-user"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-5 col-sm-5">
                    <?= $this->formLabel($this->formUsuario->get('usuario')) ?>
                    <div  class="input-group input-group-sm">
                        <?= $this->formElement($this->formUsuario->get('usuario')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-user"></i>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-4 col-sm-4">
                    <?= $this->formLabel($this->formUsuario->get('login')) ?>
                    <div  class="input-group input-group-sm">
                        <?= $this->formElement($this->formUsuario->get('login')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-user"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-4 col-sm-4">
                    <?= $this->formLabel($this->formUsuario->get('registradopor')) ?>
                    <div  class="input-group input-group-sm">
                        <?= $this->formElement($this->formUsuario->get('registradopor')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="far fa-clock"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-4 col-sm-4">
                    <?= $this->formLabel($this->formUsuario->get('fechahorareg')) ?>
                    <div  class="input-group input-group-sm">
                        <?= $this->formElement($this->formUsuario->get('fechahorareg')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="far fa-clock"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-6 col-sm-6">
                    <?= $this->formLabel($this->formUsuario->get('estado')) ?>
                    <div  class="input-group input-group-sm">
                        <?= $this->formElement($this->formUsuario->get('estado')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="far fa-clock"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-6 col-sm-6">
                    <label for="idEmpleado" class="font-weight-bold">ID Empleado</label>
                    <div class="input-group">
                        <input type="text" id="idEmpleado" name="idEmpleado" value="<?= $infoUsuario['idEmpleado'] ?>" style="color: dodgerblue;" class="form-control font-weight-bold" readonly>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-id-card"></i>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </fieldset>
        <hr>  
        <fieldset>
            <legend>Informacion de los Roles Asociados </legend> <hr>
            <div class="row border rounded-lg shadow-sm p-3">
                <div class="table-responsive" style="font-size: 11px">
                    <table id="tblUsuarioRoles" class="table table-striped table-bordered table-hover nowrap table-sm" >
                        <thead class="thead-dark">
                            <tr>
                                <th scope="col" class="text-center align-middle" style="width: 3%">ID</th>
                                <th scope="col" class="text-center align-middle">ROL</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php
                            foreach ($this->infoRoles as $rol) {
                                echo '<tr>';
                                echo '<th class="text-center align-middle">' . $rol['idRol'] . '</th>';
                                echo '<td class="text-center align-middle">' . $rol['rol'] . '</td>';
                                echo '</tr>';
                            }
                            ?>
                        </tbody>
                        <tfoot></tfoot>
                    </table>
                </div>
            </div>
        </fieldset>
    </div>
</div>
<div class="modal-footer">
    <button type="submit" class="btn btn-success" title="Activar Usuario"><i class="fas fa-unlock"></i> Desbloquear Usuario</button>
    <button type="button" class="btn btn-danger" data-dismiss="modal"><i class="far fa-times-circle"></i> Cerrar</button>
</div>
<?= $this->form()->closeTag(); ?>