<div class="container">
    <div class="row border rounded-lg shadow-sm p-3">
        <div class="table-responsive" style="font-size: 11px">
            <table  class="table table-striped table-bordered table-hover nowrap table-sm" >
                <thead class="thead-dark">
                    <tr>
                        <th scope="col" class="text-center align-middle" style="width: 3%">ID</th>
                        <th scope="col" class="text-center align-middle">ROL</th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                    foreach ($this->roles as $rol) {
                        echo '<tr>';
                        echo '<th class="text-center align-middle">' . $rol['idRol'] . '</th>';
                        echo '<td class="text-center align-middle">' . $rol['rol'] . '</td>';
                        echo '</tr>';
                    }
                    ?>
                </tbody>
                <tfoot></tfoot>
            </table>
        </div>
    </div>
</div>
<div id="msgBloqueo" style="display: none;"> 
    SU SOLICITUD ESTA SIENDO PROCESADA, POR FAVOR ESPERE...
</div>
<div class="modal fade" id="modalFormulario" data-backdrop="static" tabindex="-1" aria-labelledby="lbModalFormulario" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header bg-info text-light">
                <h5 class="modal-title" id="lbModalFormulario">Formulario</h5>
                <button type="button" class="close text-light" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div id="divContenido"></div>
        </div>
    </div>
</div>

