<?php
//--------- CARGAR MENSAJES DE ALERTA ------------------------------------------
$flash = $this->flashMessenger();
$notificaciones = [
    'success' => array_merge($flash->getSuccessMessages(), $flash->getCurrentSuccessMessages()),
    'error' => array_merge($flash->getErrorMessages(), $flash->getCurrentErrorMessages()),
    'alert' => array_merge($flash->getMessages(), $flash->getCurrentMessages()),
    'information' => array_merge($flash->getInfoMessages(), $flash->getCurrentInfoMessages()),
    'warning' => array_merge($flash->getWarningMessages(), $flash->getCurrentWarningMessages()),
];
$flash->clearCurrentMessages('default');
$flash->clearCurrentMessages('info');
$flash->clearCurrentMessages('success');
$flash->clearCurrentMessages('warning');
$flash->clearCurrentMessages('error');
$mostrarMensajes = '';
foreach (array_filter($notificaciones) as $tipo => $mensajes) {
    $tipoToastr = 'info';
    $titulo = 'Josandro';
    switch ($tipo) {
        case 'success':
            $titulo = ' OK ';
            $tipoToastr = 'success';
            break;
        case 'error':
            $titulo = ' ERROR ';
            $tipoToastr = 'error';
            break;
        case 'alert':
            $titulo = ' ALERTA ';
            $tipoToastr = 'warning';
            break;
        case 'information':
            $titulo = ' INFORMACION ';
            $tipoToastr = 'info';
            break;
        case 'warning':
            $titulo = ' PRECAUCION ';
            $tipoToastr = 'warning';
            break;
    }
    foreach ($mensajes as $mensaje) {
        $mostrarMensajes .= "toastr.$tipoToastr('$mensaje', '$titulo', {
                closeButton: true,
                debug: false,
                newestOnTop: false,
                progressBar: true,
                positionClass: 'toast-top-right',
                preventDuplicates: true,
                onclick: null,
                showDuration: '300',
                hideDuration: '1000',
                timeOut: '10000',
                extendedTimeOut: '10000',
                showEasing: 'swing',
                hideEasing: 'linear',
                showMethod: 'fadeIn',
                hideMethod: 'fadeOut'
            }); ";
    }
}
//------------------------------------------------------------------------------

$title = 'Usuarios';
$this->headTitle($title);
$this->headLink()->prependStylesheet($this->basePath('/css/select2.min.css'));
$this->headScript()->prependScript('
            $(document).ajaxStop($.unblockUI);
            $(document).ready(function() {
                $("#tabla").DataTable({
                    responsive: false,
                    iDisplayLength: 25,
                    sPaginationType: "full_numbers",
                    oLanguage: {
                        sLengthMenu: "Mostrar: _MENU_ registros por pagina",
                        sZeroRecords: "NO SE HA ENCONTRADO INFORMACION",
                        sInfo: "Mostrando <b>_START_</b> a <b>_END_</b> registros <br>TOTAL REGISTROS: <b>_TOTAL_</b> Registros</b>",
                        sInfoEmpty: "Mostrando 0 A 0 registros",
                        sInfoFiltered: "(Filtrados de un total de <b>_MAX_</b> registros)",
                        sLoadingRecords: "CARGANDO...",
                        sProcessing: "EN PROCESO...",
                        sSearch: "Buscar:",
                        sEmptyTable: "NO HAY INFORMACION DISPONIBLE PARA LA TABLA",
                        oPaginate: {
                            sFirst: "<i class=\'fa fa-fast-backward\' aria-hidden=\'true\' title=\'Inicio\'></i>",
                            sPrevious: "<i class=\'fa fa-step-backward\' aria-hidden=\'true\' title=\'Anterior\'></i>",
                            sNext: "<i class=\'fa fa-step-forward\' aria-hidden=\'true\' title=\'Siguiente\'></i>",
                            sLast: "<i class=\'fa fa-fast-forward\' aria-hidden=\'true\' title=\'Fin\'></i>",
                        }
                    },
                    aaSorting: [[0, "desc"]]
                });
                //------------------------------------------------------------------------------
                // MANIPULACION DEL EVENTO DE CIERRE DEL MODAL
                //------------------------------------------------------------------------------
                $("#modalFormulario").on("hide.bs.modal", function (e) {
                    Swal.fire({
                        title: "&iquest;DESEA CERRAR EL FORMULARIO?",
                        text: "",
                        icon: "question",
                        showCancelButton: true,
                        confirmButtonText: "Si",
                        cancelButtonText: "No",
                        allowOutsideClick: false
                    }).then((result) => {
                        if (!result.isConfirmed) {
                            $(this).modal("show");
                        }
                    });
                });
                //------------------------------------------------------------------------------
                ' . $mostrarMensajes . '
            });', 'text/javascript', array('noescape' => true))
    ->prependFile($this->basePath('/js/sistema/administracionusuario.js'))
    ->prependFile($this->basePath('/js/jquery.filterizr.min.js'))
    ->prependFile($this->basePath('/js/select2.min.js'));
?>
<?php if ($rolesUsuario['rol'] === 'SUPER_ADMINISTRADOR' || $rolesUsuario['rol'] === 'ADMINISTRADOR') { ?>
    <div class="container bg-white rounded-lg shadow-sm p-4 border">
        <div class="row">
            <div class="col-md-8 col-sm-8">
                <h1 class="display-5">Usuarios</h1>
                <hr>
                <p>En esta seccion usted puede gestionar todo lo relacionado con los datos personales de los Usuarios</p>
                <hr>
                <button type="button" onclick="verRegistrar()" class="btn btn-success" title="REGISTRAR UN NUEVO USUARIO"><i
                        class="fas fa-plus-circle"></i> Registrar Usuario</button>

            </div>
            <div class="col-md-4 col-sm-4 text-center d-none d-sm-block">
                <i class="fas fa-user-tie fa-6x border rounded-lg shadow-sm p-3 text-primary"
                    style="color: #eede00 !important;"></i>
            </div>
        </div>
    </div>
    <br>
    <div class="container">
        <div class="row border rounded-lg shadow-sm p-3">
            <div class="table-responsive" style="font-size: 11px">
                <h4>Usuarios</h4>
                <hr>
                <table id="tabla" class="table table-striped table-bordered table-hover table-sm" style="width: 100%">
                    <thead class="thead-dark">
                        <tr>
                            <th scope="col" class="text-center align-middle" style="width: 3%">ID</th>
                            <th scope="col" class="text-center align-middle" style="width: 8%"><i
                                    class="fas fa-cog fa-spin"></i></th>
                            <th scope="col" class="text-center align-middle">LOGIN</th>
                            <th scope="col" class="text-center align-middle">EMPLEADO</th>
                            <th scope="col" class="text-center align-middle">ROLES</th>
                            <th scope="col" class="text-center align-middle">FECHA <br>ULTIMO INGRESO</th>
                            <th scope="col" class="text-center align-middle">ESTADO</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php
                        foreach ($this->usuarios as $usuario) {
                            echo '<tr>';
                            echo '<th class="text-center align-middle">' . $usuario['idUsuario'] . '</th>';
                            echo '<td class="text-center align-middle">';
                            echo '<a href="javascript:verDetalle(' . $usuario['idUsuario'] . ')" title="VER DETALLE DE ESTE USUARIO"><i class="fas fa-eye" style="color: #837a06"></i></a>';
                            //echo '&nbsp;&nbsp;<a href="../usuariorol/index?idUsuario=' . $usuario['idUsuario'] . '" title="GESTIONAR ROLES DE ESTE USUARIO"><i class="fas fa-users" style="color: #837a06"></i></a>';
                            //echo '&nbsp;&nbsp;&nbsp;<a href="javascript:verCambiarSucursal(' . $usuario['idUsuario'] . ')" title="GESTIONAR SUCURSALES DE ESTE USUARIO"><i class="fas fa-house-user"></i></a>';
                            if ($rolesUsuario['rol'] == 'SUPER_ADMINISTRADOR') {
                                if ($usuario['estadoU'] == 'Activo') {
                                    echo '&nbsp;&nbsp;&nbsp;<a href="javascript:verBloquear(' . $usuario['idUsuario'] . ')" title="BLOQUEAR ESTE USUARIO"><i class="fas fa-lock" style="color: red;"></i></a>';
                                }
                                if ($usuario['estadoU'] == 'Bloqueado') {
                                    echo '&nbsp;&nbsp;&nbsp;<a href="javascript:verDesbloquear(' . $usuario['idUsuario'] . ')" title="DESBLOQUEAR ESTE USUARIO"><i class="fas fa-unlock" style="color: green;"></i></a>';
                                }
                                echo '&nbsp;&nbsp;&nbsp;<a href="javascript:verCambiarContrasena(' . $usuario['idUsuario'] . ')" title="CAMBIAR CLAVE DE ESTE USUARIO"><i class="fas fa-key" style="color: #837a06"></i></a>';
                            }
                            echo '</td>';
                            echo '<td class="text-center align-middle text-primary font-weight-bold">' . $usuario['login'] . '</td>';
                            echo '<td class="text-center align-middle">' . $usuario['empleado'] . '</td>';
                            echo '<td class="text-center align-middle">' . $usuario['roles'] . '</td>';
                            echo '<td class="text-center align-middle">' . $usuario['fechaultingreso'] . '</td>';
                            echo '<td class="text-center align-middle">' . $usuario['estadoU'] . '</td>';
                            echo '</tr>';
                        }
                        ?>
                    </tbody>
                    <tfoot></tfoot>
                </table>
            </div>
        </div>
    </div>
    <div id="msgBloqueo" style="display: none;">
        SU SOLICITUD ESTA SIENDO PROCESADA, POR FAVOR ESPERE...
    </div>
    <div class="modal fade" id="modalFormulario" data-backdrop="static" tabindex="-1" aria-labelledby="lbModalFormulario"
        aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header bg-info text-light">
                    <h5 class="modal-title" id="lbModalFormulario">Formulario</h5>
                    <button type="button" class="close text-light" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div id="divContenido"></div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="modalFormularioAux" data-backdrop="static" tabindex="-1"
        aria-labelledby="lbModalFormularioAux" aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header bg-info text-light">
                    <h5 class="modal-title" id="lbModalFormularioAux">Formulario</h5>
                    <button type="button" class="close text-light" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div id="divContenidoAux"></div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="modalFormulario2" data-backdrop="static" tabindex="-1" aria-labelledby="lbModalFormulario"
        aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header bg-info text-light">
                    <h5 class="modal-title" id="lbModalFormulario">Formulario</h5>
                    <button type="button" class="close text-light" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div id="divContenido2"></div>
            </div>
        </div>
    </div>
    <?php
} else { ?>
    <div class="container bg-white rounded-lg shadow-sm p-4 border">
        <div class="row">
            <div class="col-md-4 col-sm-4 text-center">
                <img src="<?= $this->basePath('img/areaRestringida.png'); ?>" class="rounded img-fluid" alt="Imagen"
                    style="width: 70%; height: auto">
            </div>
            <div class="col-md-8 col-sm-8"> <br><br>
                <div class="alert alert-danger text-center text-monospace" role="alert">
                    <p class="font-weight-bold">
                        USTED NO TIENE PERMISO PARA EJECUTAR LA ACCION QUE ESTA SOLICITANDO
                    </p>
                    <i class="fas fa-exclamation-triangle fa-lg"></i> &nbsp;
                    <i class="fas fa-exclamation-triangle fa-lg"></i> &nbsp;
                    <i class="fas fa-exclamation-triangle fa-lg"></i>
                </div>
                <div class="col-md-12 col-sm-12">
                    <div class="alert alert-primary text-center" role="alert">
                        Si requiere permiso por favor contactar con el Administrador del Sistema
                    </div>
                </div>
            </div>
        </div>
    </div>
    <?php
} ?>