<?php
$this->formUsuario->prepare();
echo $this->form()->openTag($this->formUsuario);
?>
<div class="modal-body ui-front" style="max-height: 450px; overflow-y: auto;">
    <div class="container-fluid">
        <fieldset>
            <legend>Informacion del Usuario </legend>
            <hr>
            <div class="form-row">
                <div class="form-group col-md-6 col-sm-6">
                    <label for="idEmpleado">Proceso *</label>
                    <div class="input-group">
                        <select class="form-control" id="idProceso" name="idProceso" onchange="getCoordinaciones()"
                            required>
                            <option value="">Seleccione...</option>
                            <?php foreach ($this->procesos as $proceso) {
                                echo "<option value='" . $proceso['idProceso'] . "'>" . $proceso['Proceso'] . "</option>";
                            } ?>
                        </select>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-id-card"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-6 col-sm-6">
                    <label for="nombre1">Coordinacion *</label>
                    <div class="input-group">
                        <select class="form-control" id="idCoordinacion" name="idCoordinacion">
                            <option value="">Seleccione...</option>
                            <?php foreach ($this->coordinaciones as $coordinacion) {
                                echo "<option value='" . $coordinacion['idCoordinacion'] . "'>" . $coordinacion['Coordinacion'] . "</option>";
                            } ?>
                        </select>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-list-ul"></i>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6 col-sm-6">
                    <label for="idEmpleado">Identificacion *</label>
                    <div class="input-group">
                        <input type="text" class="form-control" id="identificacion" name="identificacion"
                            onchange="existeIdentificacion()" required>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-id-card"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-6 col-sm-6">
                    <label for="nombre1">Primer Nombre *</label>
                    <div class="input-group">
                        <input type="text" class="form-control" id="nombre1" name="nombre1"
                            style="text-transform: uppercase;" required>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-list-ul"></i>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6 col-sm-6">
                    <label for="idEmpleado">Segundo Nombre</label>
                    <div class="input-group">
                        <input type="text" class="form-control" id="nombre2" name="nombre2"
                            style="text-transform: uppercase;">
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-list-ul"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-6 col-sm-6">
                    <label for="apellido1">Primer Apellido *</label>
                    <div class="input-group">
                        <input type="text" class="form-control" id="apellido1" name="apellido1"
                            style="text-transform: uppercase;" required>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-list-ul"></i>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6 col-sm-6">
                    <label for="idEmpleado">Segundo Apellido *</label>
                    <div class="input-group">
                        <input type="text" class="form-control" id="apellido2" name="apellido2"
                            style="text-transform: uppercase;" required>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-list-ul"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-6 col-sm-6">
                    <label for="genero">Genero *</label>
                    <div class="input-group">
                        <select class="form-control" id="genero" name="genero" required>
                            <option value="">Seleccione una opcion...</option>
                            <option value="Masculino">Masculino</option>
                            <option value="Femenino">Femenino</option>
                        </select>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-info"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-6 col-sm-6">
                    <label for="telefono">Telefono *</label>
                    <div class="input-group">
                        <input type="text" class="form-control" id="telefono" name="telefono" required>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-phone"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-6 col-sm-6">
                    <?= $this->formLabel($this->formUsuario->get('idRol')) ?>
                    <div class="input-group">
                        <?= $this->formElement($this->formUsuario->get('idRol')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-users"></i>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </fieldset>
        <fieldset>
            <div class="form-row">
                <div class="form-group col-md-6 col-sm-6" hidden>
                    <?= $this->formLabel($this->formUsuario->get('idEmpleado')) ?>
                    <div class="input-group">
                        <?= $this->formElement($this->formUsuario->get('idEmpleado')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-user"></i>
                            </span>
                        </div>
                    </div>
                </div>

            </div>
        </fieldset>
    </div>
    <div class="alert alert-primary text text" role="alert">
        <p class="font-weight-bold">
            <i class="fas fa-info-circle"></i>
            Cuando se registre un nuevo usuario se generará un usuario y contraseña predeterminado.
        </p>
        <p class="font-weight-bold">Ejemplo:</p> Usuario: jpepito | Contraseña: jpepito*2026
    </div>
</div>
<div class="modal-footer">
    <button type="submit" class="btn btn-success" title="Registrar Usuario"><i class="fas fa-save"></i> Registrar
        Usuario</button>
    <button type="button" class="btn btn-danger" data-dismiss="modal"><i class="far fa-times-circle"></i>
        Cerrar</button>
</div>
<?= $this->form()->closeTag(); ?>