<?php
//--------- CARGAR MENSAJES DE ALERTA ------------------------------------------
$flash = $this->flashMessenger();
$notificaciones = [
    'success' => array_merge($flash->getSuccessMessages(), $flash->getCurrentSuccessMessages()),
    'error' => array_merge($flash->getErrorMessages(), $flash->getCurrentErrorMessages()),
    'alert' => array_merge($flash->getMessages(), $flash->getCurrentMessages()),
    'information' => array_merge($flash->getInfoMessages(), $flash->getCurrentInfoMessages()),
    'warning' => array_merge($flash->getWarningMessages(), $flash->getCurrentWarningMessages()),
];
$flash->clearCurrentMessages('default');
$flash->clearCurrentMessages('info');
$flash->clearCurrentMessages('success');
$flash->clearCurrentMessages('warning');
$flash->clearCurrentMessages('error');
$mostrarMensajes = '';
foreach (array_filter($notificaciones) as $tipo => $mensajes) {
    $tipoToastr = 'info';
    $titulo = 'App-Masclick';
    switch ($tipo) {
        case 'success':
            $titulo = ' OK ';
            $tipoToastr = 'success';
            break;
        case 'error':
            $titulo = ' ERROR ';
            $tipoToastr = 'error';
            break;
        case 'alert':
            $titulo = ' ALERTA ';
            $tipoToastr = 'warning';
            break;
        case 'information':
            $titulo = ' INFORMACION ';
            $tipoToastr = 'info';
            break;
        case 'warning':
            $titulo = ' PRECAUCION ';
            $tipoToastr = 'warning';
            break;
    }
    foreach ($mensajes as $mensaje) {
        $mostrarMensajes .= "toastr.$tipo('$mensaje', '$titulo', {
                closeButton: true,
                debug: false,
                newestOnTop: false,
                progressBar: true,
                positionClass: 'toast-top-full-width',
                preventDuplicates: false,
                onclick: null,
                showDuration: '300',
                hideDuration: '1000',
                timeOut: '8000',
                extendedTimeOut: '1000',
                showEasing: 'swing',
                hideEasing: 'linear',
                showMethod: 'fadeIn',
                hideMethod: 'fadeOut'
            }); ";
    }
}
//------------------------------------------------------------------------------

$title = 'Equipos Celulares';
$this->headTitle($title);
$this->headLink()->prependStylesheet($this->basePath('/css/select2.min.css'));
$this->headScript()->prependScript('
            $(document).ajaxStop($.unblockUI);
            $(document).ready(function() {
                $("#tabla").DataTable({
                    responsive: false,
                    iDisplayLength: 25,
                    sPaginationType: "full_numbers",
                    oLanguage: {
                        sLengthMenu: "Mostrar: _MENU_ registros por pagina",
                        sZeroRecords: "NO SE HA ENCONTRADO INFORMACION",
                        sInfo: "Mostrando <b>_START_</b> a <b>_END_</b> registros <br>TOTAL REGISTROS: <b>_TOTAL_</b> Registros</b>",
                        sInfoEmpty: "Mostrando 0 A 0 registros",
                        sInfoFiltered: "(Filtrados de un total de <b>_MAX_</b> registros)",
                        sLoadingRecords: "CARGANDO...",
                        sProcessing: "EN PROCESO...",
                        sSearch: "Buscar:",
                        sEmptyTable: "NO HAY INFORMACION DISPONIBLE PARA LA TABLA",
                        oPaginate: {
                            sFirst: "<i class=\'fa fa-fast-backward\' aria-hidden=\'true\' title=\'Inicio\'></i>",
                            sPrevious: "<i class=\'fa fa-step-backward\' aria-hidden=\'true\' title=\'Anterior\'></i>",
                            sNext: "<i class=\'fa fa-step-forward\' aria-hidden=\'true\' title=\'Siguiente\'></i>",
                            sLast: "<i class=\'fa fa-fast-forward\' aria-hidden=\'true\' title=\'Fin\'></i>",
                        }
                    },
                    aaSorting: [[0, "desc"]]
                });
                //------------------------------------------------------------------------------
                // MANIPULACION DEL EVENTO DE CIERRE DEL MODAL
                //------------------------------------------------------------------------------
                $("#modalFormulario").on("hide.bs.modal", function (e) {
                    Swal.fire({
                        title: "&iquest;DESEA CERRAR EL FORMULARIO?",
                        text: "",
                        icon: "question",
                        showCancelButton: true,
                        confirmButtonText: "Si",
                        cancelButtonText: "No",
                        allowOutsideClick: false
                    }).then((result) => {
                        if (!result.isConfirmed) {
                            $(this).modal("show");
                        }
                    });
                });
                //------------------------------------------------------------------------------
                ' . $mostrarMensajes . '
            });', 'text/javascript', array('noescape' => true))
        ->prependFile($this->basePath('/js/sistema/equipo.js'))
        ->prependFile($this->basePath('/js/filterizr.min.js'))
        ->prependFile($this->basePath('/js/jquery.filterizr.min.js'))
        ->prependFile($this->basePath('/js/select2.min.js'));
?>
<div class="container bg-white rounded-lg shadow-sm p-4 border">
    <div class="row">        
        <div class="col-md-8 col-sm-8">
            <h1 class="display-5">Equipos [<small class="text-primary">Disponibles</small>]</h1>
            <p>En esta seccion usted puede gestionar todo lo relacionado con los <b>Equipos Celulares</b>  registrados en el sistema</p> <hr>
        </div>
        <div class="col-md-4 col-sm-4 text-center d-none d-sm-block">
            <i class="fas fa-mobile-alt fa-6x border rounded-lg shadow-sm p-3 text-primary"></i>
        </div>
    </div>
</div> <br>
<div class="container">
    <div class="row border rounded-lg shadow-sm p-3">
        <div class="table-responsive" style="font-size: 11px">
            <h5 class="text-primary">Equipos Encontrados ( <small class="text-danger">EQUIPOS: <b id="contEquipos">0</b> &nbsp; <b class="text-primary">|</b> &nbsp; TOTAL EQUIPOS: <b id="vlrTotalEquipos">$0</b></small> )</h5> <hr>
            <table id="tabla" class="table table-striped table-bordered table-hover table-sm" style="width: 100%">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col" class="text-center align-middle" style="width: 3%">ID</th>
                        <th scope="col" class="text-center align-middle" style="width: 8%"><i class="fas fa-cog fa-spin"></i></th>
                        <th scope="col" class="text-center align-middle">BODEGA</th>
                        <th scope="col" class="text-center align-middle">EQUIPO</th>
                        <th scope="col" class="text-center align-middle">SERIAL</th>
                        <th scope="col" class="text-center align-middle">VALOR UNITARIO</th>
                        <th scope="col" class="text-center align-middle">ESTADO</th>
                        <th scope="col" class="text-center align-middle">REGISTRADO POR</th>
                        <th scope="col" class="text-center align-middle">FECHA REGISTRO</th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                    $vlrTotalEquipos = 0;
                    foreach ($this->celulares as $celular) {
                        $vlrTotalEquipos = $vlrTotalEquipos + intval($celular['vlrunitario']);
                        echo '<tr>';
                        echo '<th class="text-center" scope="row">' . $celular['idCelular'] . '</th>';
                        echo '<td class="text-center align-middle">';
                        echo '<a href="javascript:verDetalle(' . $celular['idCelular'] . ')" title="VER DETALLE DE ESTE EQUIPO"><i class="fas fa-eye"></i></a>';
                        echo '</td>';
                        echo '<td class="text-center align-middle">' . $celular['sucursal'] . '</td>';
                        echo '<td class="text-center align-middle text-primary">' . $celular['tipo'] . ' ' . $celular['marca'] . '<br>' . $celular['referencia'] . ' ' . $celular['color'] . ' ' . $celular['almacenamiento'] . ' GB</td>';
                        echo '<td class="text-center align-middle font-weight-bold">' . $celular['serial'] . '</td>';
                        echo '<td class="text-center align-middle text-danger">' . number_format($celular['vlrunitario']) . '</td>';
                        echo '<td class="text-center align-middle font-weight-bold">' . $celular['estado'] . '</td>';
                        echo '<td class="text-center align-middle">' . $celular['registradopor'] . '</td>';
                        echo '<td class="text-center align-middle">' . $celular['fechahorareg'] . '</td>';
                        echo '</tr>';
                    }
                    ?>
                </tbody>
                <tfoot></tfoot>
            </table>
        </div>
    </div>
</div>

<div id="msgBloqueo" style="display: none;">
    SU SOLICITUD ESTA SIENDO PROCESADA, POR FAVOR ESPERE...
</div>

<div class="modal fade" id="modalFormulario" data-backdrop="static" tabindex="-1" aria-labelledby="lbModalFormulario" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header bg-info text-light">
                <h5 class="modal-title" id="lbModalFormulario">Formulario</h5>
                <button type="button" class="close text-light" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div id="divContenido"></div>
        </div>
    </div>
</div>
<div class="modal fade" id="modalFormularioAux" data-backdrop="static" tabindex="-1" aria-labelledby="lbModalFormulario2" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header bg-info text-light">
                <h5 class="modal-title" id="lbModalFormularioAux">Formulario</h5>
                <button type="button" class="close text-light" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div id="divContenidoAux"></div>
        </div>
    </div>
</div>
<?php
echo '<script>';
echo '$("#vlrTotalEquipos").html("$' . number_format($vlrTotalEquipos) . '");';
echo '$("#contEquipos").html("' . number_format(count($this->celulares)) . '");';
echo '</script>';
?>
