<div class="container"> <br>
    <div class="row">
        <div class="col-md-4 col-sm-4 text-center">
            <img src="<?= $this->basePath('img/areaRestringida.png'); ?>" class="rounded img-fluid" alt="Imagen" style="width: 70%; height: auto">
        </div>
        <div class="col-md-8 col-sm-8"> <br><br>
            <div class="alert alert-danger text-center text-monospace" role="alert">
                <p class="font-weight-bold">
                    USTED NO TIENE PERMISO PARA EJECUTAR LA ACCION QUE ESTA SOLICITANDO
                </p>
                <i class="fas fa-exclamation-triangle fa-lg"></i> &nbsp; 
                <i class="fas fa-exclamation-triangle fa-lg"></i> &nbsp; 
                <i class="fas fa-exclamation-triangle fa-lg"></i>
            </div>
            <div class="col-md-12 col-sm-12">
                <div class="alert alert-primary text-center" role="alert">
                    Si requiere permiso por favor contactar con el Administrador del Sistema
                </div>
            </div>
        </div>
    </div> <hr>
</div>