
<?php
//--------- CARGAR MENSAJES DE ALERTA ------------------------------------------
$flash = $this->flashMessenger();
$notificaciones = [
    'success' => array_merge($flash->getSuccessMessages(), $flash->getCurrentSuccessMessages()),
    'error' => array_merge($flash->getErrorMessages(), $flash->getCurrentErrorMessages()),
    'alert' => array_merge($flash->getMessages(), $flash->getCurrentMessages()),
    'information' => array_merge($flash->getInfoMessages(), $flash->getCurrentInfoMessages()),
    'warning' => array_merge($flash->getWarningMessages(), $flash->getCurrentWarningMessages()),
];
$flash->clearCurrentMessages('default');
$flash->clearCurrentMessages('info');
$flash->clearCurrentMessages('success');
$flash->clearCurrentMessages('warning');
$flash->clearCurrentMessages('error');
$mostrarMensajes = '';
foreach (array_filter($notificaciones) as $tipo => $mensajes) {
    $tipoToastr = 'info';
    $titulo = 'Josandro';
    switch ($tipo) {
        case 'success':
            $titulo = ' OK ';
            $tipoToastr = 'success';
            break;
        case 'error':
            $titulo = ' ERROR ';
            $tipoToastr = 'error';
            break;
        case 'alert':
            $titulo = ' ALERTA ';
            $tipoToastr = 'warning';
            break;
        case 'information':
            $titulo = ' INFORMACION ';
            $tipoToastr = 'info';
            break;
        case 'warning':
            $titulo = ' PRECAUCION ';
            $tipoToastr = 'warning';
            break;
    }
    foreach ($mensajes as $mensaje) {
        $mostrarMensajes .= "toastr.$tipoToastr('$mensaje', '$titulo', {
                closeButton: true,
                debug: false,
                newestOnTop: false,
                progressBar: true,
                positionClass: 'toast-top-right',
                preventDuplicates: true,
                onclick: null,
                showDuration: '300',
                hideDuration: '1000',
                timeOut: '10000',
                extendedTimeOut: '10000',
                showEasing: 'swing',
                hideEasing: 'linear',
                showMethod: 'fadeIn',
                hideMethod: 'fadeOut'
            }); ";
    }
}
//------------------------------------------------------------------------------

$title = 'Promociones';
$this->headTitle($title);
$this->headLink()->prependStylesheet($this->basePath('/css/select2.min.css'));
$this->headScript()->prependScript('
            $(document).ajaxStop($.unblockUI);
            $(document).ready(function() {
                $("#tabla").DataTable({
                    responsive: false,
                    iDisplayLength: 25,
                    sPaginationType: "full_numbers",
                    oLanguage: {
                        sLengthMenu: "Mostrar: _MENU_ registros por pagina",
                        sZeroRecords: "NO SE HA ENCONTRADO INFORMACION",
                        sInfo: "Mostrando <b>_START_</b> a <b>_END_</b> registros <br>TOTAL REGISTROS: <b>_TOTAL_</b> Registros</b>",
                        sInfoEmpty: "Mostrando 0 A 0 registros",
                        sInfoFiltered: "(Filtrados de un total de <b>_MAX_</b> registros)",
                        sLoadingRecords: "CARGANDO...",
                        sProcessing: "EN PROCESO...",
                        sSearch: "Buscar:",
                        sEmptyTable: "NO HAY INFORMACION DISPONIBLE PARA LA TABLA",
                        oPaginate: {
                            sFirst: "<i class=\'fa fa-fast-backward\' aria-hidden=\'true\' title=\'Inicio\'></i>",
                            sPrevious: "<i class=\'fa fa-step-backward\' aria-hidden=\'true\' title=\'Anterior\'></i>",
                            sNext: "<i class=\'fa fa-step-forward\' aria-hidden=\'true\' title=\'Siguiente\'></i>",
                            sLast: "<i class=\'fa fa-fast-forward\' aria-hidden=\'true\' title=\'Fin\'></i>",
                        }
                    },
                    aaSorting: [[0, "desc"]]
                });
                //------------------------------------------------------------------------------
                // MANIPULACION DEL EVENTO DE CIERRE DEL MODAL
                //------------------------------------------------------------------------------
                $("#modalFormulario").on("hide.bs.modal", function (e) {
                    Swal.fire({
                        title: "&iquest;DESEA CERRAR EL FORMULARIO?",
                        text: "",
                        icon: "question",
                        showCancelButton: true,
                        confirmButtonText: "Si",
                        cancelButtonText: "No",
                        allowOutsideClick: false
                    }).then((result) => {
                        if (!result.isConfirmed) {
                            $(this).modal("show");
                        }
                    });
                });
                //------------------------------------------------------------------------------
                ' . $mostrarMensajes . '
            });', 'text/javascript', array('noescape' => true))
        ->prependFile($this->basePath('/js/sistema/usuariorol.js'))
        ->prependFile($this->basePath('/js/jquery.filterizr.min.js'))
        ->prependFile($this->basePath('/js/select2.min.js'));
?>
<div class="container bg-white rounded-lg shadow-sm p-4 border">
    <h3><i class="fas fa-users fa-lg bg-white rounded-lg shadow p-3 text-primary"></i> &nbsp; GESTION DE USUARIOS [<small class="text-primary">ROLES</small>]</h3> <hr>
    <fieldset>
        <h4 class="text-primary">Informacion de Usuarios y Sus Roles </h4> <hr>
        <div class="form-row">
            <div class="form-group col-md-2 col-sm-2">
                <label for="idUsuarioAux" class="text-primary font-weight-bold">ID Usuario</label>
                <div class="input-group input-group-sm">
                    <input type="text" id="idUsuarioAux" name="idUsuarioAux" value="<?= $this->infoUsuario['idUsuario'] ?>" class="form-control font-weight-bold" readonly>
                    <div class="input-group-append">
                        <span class="input-group-text">
                            <i class="fas fa-key"></i>
                        </span>
                    </div>
                </div>
            </div>
            <div class="form-group col-md-5 col-sm-5">
                <label for="loginAux" class="text-primary font-weight-bold">Login</label>
                <div class="input-group input-group-sm">
                    <input type="text" id="loginAux" name="loginAux" value="<?= $this->infoUsuario['login'] ?>" class="form-control font-weight-bold" readonly>
                    <div class="input-group-append">
                        <span class="input-group-text">
                            <i class="fas fa-user"></i>
                        </span>
                    </div>
                </div>
            </div>
            <div class="form-group col-md-5 col-sm-5">
                <label for="empleadoAux" class="text-primary font-weight-bold">Empleado</label>
                <div class="input-group input-group-sm">
                    <input type="text" id="empleadoAux" name="empleadoAux" value="<?= $this->infoUsuario['empleado'] ?>" class="form-control font-weight-bold" readonly>
                    <div class="input-group-append">
                        <span class="input-group-text">
                            <i class="fas fa-user"></i>
                        </span>
                    </div>
                </div>
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-6 col-sm-6">
                <label for="registradoporAux">Registrado por</label>
                <div  class="input-group input-group-sm">
                    <input type="text" id="registradoporAux" name="registradoporAux" value="<?= $this->infoUsuario['registradopor'] ?>" class="form-control" readonly>
                    <div class="input-group-append">
                        <span class="input-group-text">
                            <i class="fas fa-user"></i>
                        </span>
                    </div>
                </div>
            </div>
            <div class="form-group col-md-6 col-sm-6">
                <label for="fechahoraregAux">Fecha Registro</label>
                <div  class="input-group input-group-sm">
                    <input type="text" id="fechahoraregAux" name="fechahoraregAux" value="<?= $this->infoUsuario['fechahorareg'] ?>" class="form-control" readonly>
                    <div class="input-group-append">
                        <span class="input-group-text">
                            <i class="far fa-clock"></i>
                        </span>
                    </div>
                </div>
            </div>
        </div>
    </fieldset> <hr>
    <button type="button" onclick="location.href = '../administracion/index'" class="btn btn-warning" title="REGRESAR A LA SECCION DE ADMINISTRACION"><i class="fas fa-chevron-left"></i> Regresar</button>
    <button type="button" onclick="verRegistrar(<?= $this->infoUsuario['idUsuario'] ?>)" class="btn btn-success" title="ASIGNAR ROL AL USUARIO"><i class="fas fa-plus-circle"></i> Asignar Rol</button>
</div>
<br>
<div class="container">
    <div class="row border rounded-lg shadow-sm p-3">
        <div class="table-responsive" style="font-size: 11px">
            <h4>Roles Asociados</h4> <hr>
            <table id="tabla" class="table table-striped table-bordered table-hover table-sm" style="width: 100%">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col" class="text-center align-middle" style="width: 3%">ID</th>
                        <th scope="col" class="text-center align-middle" style="width: 8%"><i class="fas fa-cog fa-spin"></i></th>
                        <th scope="col" class="text-center align-middle">USUARIO</th>                               
                        <th scope="col" class="text-center align-middle">ROL</th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                    foreach ($this->infoRoles as $rol) {
                        echo '<tr>';
                        echo '<th class="text-center align-middle">' . $rol['idUsuario'] . '</th>';
                        echo '<td class="text-center align-middle">';
                        echo '<a href="javascript:verDetalle(' . $rol['idUsuario'] . ',' . $rol['idRol'] . ')" title="VER DETALLE DEL ROL"><i class="fas fa-eye"></i></a>';
                        echo '&nbsp;&nbsp;&nbsp;<a href="javascript:verEliminar(' . $rol['idUsuario'] . ',', $rol['idRol'] . ')" title="VER ELIMINAR PARA EL ROL ASOCIADO AL USUARIO"><i style="color: red" class="fas fa-times-circle"></i></a>';
                        echo '</td>';
                        echo '<td class="text-center align-middle">' . $rol['usuario'] . '</td>';
                        echo '<td class="text-center align-middle">' . $rol['rol'] . '</td>';
                        echo '</tr>';
                    }
                    ?>
                </tbody>
                <tfoot></tfoot>
            </table>
        </div>
    </div>
</div>
<div id="msgBloqueo" style="display: none;">
    SU SOLICITUD ESTA SIENDO PROCESADA, POR FAVOR ESPERE...
</div>
<div class="modal fade" id="modalFormulario" data-backdrop="static" tabindex="-1" aria-labelledby="lbModalFormulario" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header bg-info text-light">
                <h5 class="modal-title" id="lbModalFormulario">Formulario</h5>
                <button type="button" class="close text-light" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div id="divContenido"></div>
        </div>
    </div>
</div>
<div class="modal fade" id="modalFormularioAux" data-backdrop="static" tabindex="-1" aria-labelledby="lbModalFormularioAux" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header bg-info text-light">
                <h5 class="modal-title" id="lbModalFormularioAux">Formulario</h5>
                <button type="button" class="close text-light" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div id="divContenidoAux"></div>
        </div>
    </div>
</div>
<div class="modal fade" id="modalFormulario2" data-backdrop="static" tabindex="-1" aria-labelledby="lbModalFormulario" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header bg-info text-light">
                <h5 class="modal-title" id="lbModalFormulario">Formulario</h5>
                <button type="button" class="close text-light" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div id="divContenido2"></div>
        </div>
    </div>
</div>

