<?php

$this->formResultados->prepare();
$this->formResultados->setAttribute('action', $this->url('indicadores/resultados', ['action' => 'editar']));
echo $this->form()->openTag($this->formResultados);
?>

<div class="modal-body ui-front" style="max-height: 450px; overflow-y: auto;">
    <div class="container-fluid">
        <fieldset>
            <legend>Informacion del Resultado</legend>
            <hr>
            <div style="display:none;">
                <?= $this->formElement($this->formResultados->get('registradopor')) ?>
                <?= $this->formElement($this->formResultados->get('FechaRegistro')) ?>
                <?= $this->formElement($this->formResultados->get('id_indicador')) ?>
            </div>


            <div class="form-row">
                <div class="form-group col-md-4">
                    <label>ID Resultado</label>
                    <div class="input-group">
                        <?= $this->formElement($this->formResultados->get('id_result')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text"><i class="fas fa-hashtag"></i></span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-4">
                    <?= $this->formLabel($this->formResultados->get('num')) ?>
                    <div class="input-group">
                        <?= $this->formElement($this->formResultados->get('num')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-align-left"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-4">
                    <?= $this->formLabel($this->formResultados->get('dem')) ?>
                    <div class="input-group">
                        <?= $this->formElement($this->formResultados->get('dem')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-align-left"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-8">
                    <?= $this->formLabel($this->formResultados->get('mes')) ?>
                    <div class="input-group">
                        <?= $this->formElement($this->formResultados->get('mes')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-align-left"></i>
                            </span>
                        </div>
                    </div>
                </div>


                <div class="form-group col-md-4">
                    <?= $this->formLabel($this->formResultados->get('resultado')) ?>
                    <div class="input-group">
                        <?= $this->formElement($this->formResultados->get('resultado')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-align-left"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-12">
                    <?= $this->formLabel($this->formResultados->get('analisis')) ?>
                    <div class="input-group">
                        <?= $this->formElement($this->formResultados->get('analisis')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-align-left"></i>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </fieldset>
        <legend>Informacion del Registro</legend>
        <hr>
        <div class="form-row">
            <div class="form-group col-md-6">
                <label>Registrado Por</label>
                <div class="input-group">
                    <input type="text" class="form-control"
                        value="<?= $this->formResultados->get('registradopor')->getValue() ?>" readonly>
                    <div class="input-group-append">
                        <span class="input-group-text"><i class="fas fa-user"></i></span>
                    </div>
                </div>
            </div>
            <div class="form-group col-md-6">
                <label>Fecha de Registro</label>
                <div class="input-group">
                    <input type="text" class="form-control"
                        value="<?= $this->formResultados->get('FechaRegistro')->getValue() ?>" readonly>
                    <div class="input-group-append">
                        <span class="input-group-text"><i class="far fa-clock"></i></span>
                    </div>
                </div>
            </div>
        </div>

        <?php if ($this->formResultados->get('modificadopor')->getValue()): ?>
            <!-- Fila 4: Modificación (Solo si existe) -->
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label>Modificado Por</label>
                    <div class="input-group">
                        <input type="text" class="form-control"
                            value="<?= $this->formResultados->get('modificadopor')->getValue() ?>" readonly>
                        <div class="input-group-append">
                            <span class="input-group-text"><i class="fas fa-user-edit"></i></span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-6">
                    <label>Fecha de Modificación</label>
                    <div class="input-group">
                        <input type="text" class="form-control"
                            value="<?= $this->formResultados->get('fechahoramod')->getValue() ?>" readonly>
                        <div class="input-group-append">
                            <span class="input-group-text"><i class="far fa-clock"></i></span>
                        </div>
                    </div>
                </div>
            </div>
        <?php endif; ?>
    </div>
</div>

<div class="modal-footer">
    <button type="submit" class="btn btn-primary" title="GUARDAR CAMBIOS">
        <i class="fas fa-save"></i> Guardar Cambios
    </button>
    <button type="button" class="btn btn-secondary" data-dismiss="modal">
        <i class="far fa-times-circle"></i> Cancelar
    </button>
</div>

<?= $this->form()->closeTag(); ?>

<script>

    $("input").keydown(function (e) {
        if (e.which === 13) {
            event.preventDefault();
            return false;
        }
    });
</script>