<?php
//--------- CARGAR MENSAJES DE ALERTA ------------------------------------------
$flash = $this->flashMessenger();
$notificaciones = [
    'success' => array_merge($flash->getSuccessMessages(), $flash->getCurrentSuccessMessages()),
    'error' => array_merge($flash->getErrorMessages(), $flash->getCurrentErrorMessages()),
    'alert' => array_merge($flash->getMessages(), $flash->getCurrentMessages()),
    'information' => array_merge($flash->getInfoMessages(), $flash->getCurrentInfoMessages()),
    'warning' => array_merge($flash->getWarningMessages(), $flash->getCurrentWarningMessages()),
];
$flash->clearCurrentMessages('default');
$flash->clearCurrentMessages('info');
$flash->clearCurrentMessages('success');
$flash->clearCurrentMessages('warning');
$flash->clearCurrentMessages('error');
$mostrarMensajes = '';
foreach (array_filter($notificaciones) as $tipo => $mensajes) {
    $tipoToastr = 'info';
    $titulo = 'Usuarios';
    switch ($tipo) {
        case 'success':
            $titulo = ' OK ';
            $tipoToastr = 'success';
            break;
        case 'error':
            $titulo = ' ERROR ';
            $tipoToastr = 'error';
            break;
        case 'alert':
            $titulo = ' ALERTA ';
            $tipoToastr = 'warning';
            break;
        case 'information':
            $titulo = ' INFORMACION ';
            $tipoToastr = 'info';
            break;
        case 'warning':
            $titulo = ' PRECAUCION ';
            $tipoToastr = 'warning';
            break;
    }
    foreach ($mensajes as $mensaje) {
        $mostrarMensajes .= "toastr.$tipoToastr('$mensaje', '$titulo', {
                closeButton: true,
                debug: false,
                newestOnTop: false,
                progressBar: true,
                positionClass: 'toast-top-right',
                preventDuplicates: true,
                onclick: null,
                showDuration: '300',
                hideDuration: '1000',
                timeOut: '10000',
                extendedTimeOut: '10000',
                showEasing: 'swing',
                hideEasing: 'linear',
                showMethod: 'fadeIn',
                hideMethod: 'fadeOut'
            }); ";
    }
}
//------------------------------------------------------------------------------

$title = 'Usuarios';
$this->headTitle($title);
$this->headScript()->prependScript('
            $(document).ajaxStop($.unblockUI);
            $(document).ready(function() {
                //------------------------------------------------------------------------------
                // MANIPULACION DEL EVENTO DE CIERRE DEL MODAL
                //------------------------------------------------------------------------------
                $("#modalFormulario").on("hide.bs.modal", function (e) {
                    Swal.fire({
                        title: "DESEA CERRAR EL FORMULARIO ?",
                        text: "",
                        icon: "question",
                        showCancelButton: true,
                        confirmButtonText: "Si",
                        cancelButtonText: "No",
                        allowOutsideClick: false
                    }).then((result) => {
                        if (!result.isConfirmed) {
                            $(this).modal("show");
                        }
                    });
                });
                //------------------------------------------------------------------------------
                ' . $mostrarMensajes . '
            });', 'text/javascript', array('noescape' => true))
    ->prependFile($this->basePath('/js/sistema/bandejaEntrada.js'));
?>
<div class="container bg-white rounded-lg shadow-sm p-4 border">
    <h3><i class="fas fa-network-wired fa-lg bg-white rounded-lg shadow p-3 text-primary"
            style="color: #eede00 !important;"></i> &nbsp; MODULO DE USUARIOS
    </h3>
</div> <br>
<div class="container bg-white">
    <div class="border rounded-lg shadow-sm p-3">
        <div class="row row-cols-1 row-cols-md-4">
            <div class="col mb-4">
                <div class="card h-100 border shadow-sm text-center d-flex justify-content-center align-items-center"
                    onmouseover="$(this).removeClass('shadow-sm').addClass('shadow')"
                    onmouseout="$(this).removeClass('shadow').addClass('shadow-sm')">

                    <a href="<?= $this->url('usuarios/administracion', ['action' => 'index']) ?>"
                        class="text-decoration-none hvr-float-shadow">

                        <div class="card-body d-flex flex-column justify-content-center align-items-center">

                            <i class="fas fa-users fa-4x text-primary mb-3" style="color: #eede00 !important;"></i>

                            <h5 class="text-dark m-0">USUARIOS</h5>

                        </div>
                    </a>
                </div>
            </div>
            <?php if ($rolesUsuario['rol'] === 'SUPER_ADMINISTRADOR') { ?>
                <div class="col mb-4">
                    <div class="card h-100 border shadow-sm text-center d-flex justify-content-center align-items-center"
                        onmouseover="$(this).removeClass('shadow-sm').addClass('shadow')"
                        onmouseout="$(this).removeClass('shadow').addClass('shadow-sm')">

                        <a href="<?= $this->url('usuarios/roles', ['action' => 'index']) ?>"
                            class="text-decoration-none hvr-float-shadow">

                            <div class="card-body d-flex flex-column justify-content-center align-items-center">

                                <i class="fas fa-user-cog fa-4x text-primary mb-3" style="color: #eede00 !important;"></i>

                                <h5 class="text-dark m-0">ROLES</h5>

                            </div>
                        </a>
                    </div>
                </div>
            
                <!-- <div class="col mb-4">
                    <div class="card h-100 border shadow-sm text-center d-flex justify-content-center align-items-center"
                        onmouseover="$(this).removeClass('shadow-sm').addClass('shadow')"
                        onmouseout="$(this).removeClass('shadow').addClass('shadow-sm')">

                        <a href="< ?= $this->url('usuarios/recursosrbac', ['action' => 'index']) ?>"
                            class="text-decoration-none hvr-float-shadow">

                            <div class="card-body d-flex flex-column justify-content-center align-items-center">

                                <i class="fas fa-user-lock fa-4x text-primary mb-3" style="color: #eede00 !important;"></i>

                                <h5 class="text-dark m-0">PERMISOS</h5>

                            </div>
                        </a>
                    </div>
                </div>
 -->            <?php } ?>
        </div>
    </div>
</div>
</div>
<div id="msgBloqueo" style="display: none;">
    SU SOLICITUD ESTA SIENDO PROCESADA, POR FAVOR ESPERE...
</div>

<div class="modal fade" id="modalFormulario" data-backdrop="static" tabindex="-1" aria-labelledby="lbModalFormulario"
    aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header bg-info text-light">
                <h5 class="modal-title" id="lbModalFormulario">Formulario</h5>
                <button type="button" class="close text-light" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div id="divContenido"></div>
        </div>
    </div>
</div>