<?php
$this->formResponsable->prepare();
echo $this->form()->openTag($this->formResponsable);
?>
<div class="modal-body ui-front" style="max-height: 450px; overflow-y: auto;">
    <div class="container-fluid">
        <fieldset>
            <legend>Informacion de la asignacion </legend>
            <hr>
            <div class="form-row">
                <div class="form-group col-md-6 col-sm-6">
                    <?= $this->formLabel($this->formResponsable->get('idDireccion')) ?>
                    <div class="input-group">
                        <?= $this->formSelect($this->formResponsable->get('idDireccion')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-building"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-6 col-sm-6">
                    <?= $this->formLabel($this->formResponsable->get('idCoordinacion')) ?>
                    <div class="input-group">
                        <?= $this->formSelect($this->formResponsable->get('idCoordinacion')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-users"></i>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
            <hr>
            <fieldset>
                <legend>Busqueda de Correo</legend>
                <hr>
                <div class="form-row">
                    <div class="form-group col-md-6 col-sm-6">
                        <label for="correoBusqAux">Correo</label>
                        <div class="input-group">
                            <input type="email" id="correoBusqAux" name="correoBusqAux" value="" class="form-control">
                            <div class="input-group-append">
                                <button type="button" id="btnBuscarByCorreo" onclick="buscarByCorreo()"
                                    class="btn btn-primary">
                                    <i class="fas fa-search"></i>
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="alert alert-warning" role="alert">
                    Recuerde que si el correo no existe en el sistema debe registrarlo de lo
                    contrario solo busque el correo
                </div>
                <div id="divInfoCorreo"></div>
                <!-- <div class="form-group col-md-6 col-sm-6">
                    < ?= $this->formLabel($this->formResponsable->get('idResponsable')) ?>
                    <div class="input-group">
                        < ?= $this->formSelect($this->formResponsable->get('idResponsable')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-user"></i>
                            </span>
                        </div>
                    </div>
                </div> -->
            </fieldset>
    </div>

    </fieldset>
    <?= $this->formHidden($this->formResponsable->get('idReporte')) ?>
</div>
<div class="modal-footer">
    <button type="submit" class="btn btn-success" title="Asignar Reporte"><i class="fas fa-check"></i> Asignar
        Reporte</button>
    <button type="button" class="btn btn-danger" data-dismiss="modal"><i class="far fa-times-circle"></i>
        Cerrar</button>
</div>
<script>
    $(document).ready(function () {
        validarYBloquear();
    });
</script>
<?= $this->form()->closeTag(); ?>