<div class="modal-body ui-front" style="max-height: 450px; overflow-y: auto;">
    <div class="container-fluid">
        <fieldset>
            <legend>Información del Reporte</legend>
            <hr>
            <?= $this->formHidden($this->formReportes->get('idReporte')) ?>

            <div class="form-row">
                <div class="form-group col-md-6 col-sm-6">
                    <?= $this->formLabel($this->formReportes->get('nombre_reporte')) ?>
                    <div class="input-group">
                        <?= $this->formElement($this->formReportes->get('nombre_reporte')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-book"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-6 col-sm-6">
                    <?= $this->formLabel($this->formReportes->get('nombre_archivo')) ?>
                    <div class="input-group">
                        <?= $this->formElement($this->formReportes->get('nombre_archivo')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-file-alt"></i>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6 col-sm-6">
                    <?= $this->formLabel($this->formReportes->get('plataforma')) ?>
                    <div class="input-group">
                        <?= $this->formElement($this->formReportes->get('plataforma')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-globe"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-6 col-sm-6">
                    <?= $this->formLabel($this->formReportes->get('firmas_requeridas')) ?>
                    <div class="input-group">
                        <?= $this->formElement($this->formReportes->get('firmas_requeridas')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-file-signature"></i>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6 col-sm-6">
                    <?= $this->formLabel($this->formReportes->get('periodicidad')) ?>
                    <div class="input-group">
                        <?= $this->formElement($this->formReportes->get('periodicidad')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-calendar-alt"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-6 col-sm-6">
                    <?= $this->formLabel($this->formReportes->get('normatividad')) ?>
                    <div class="input-group">
                        <?= $this->formElement($this->formReportes->get('normatividad')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-gavel"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-6 col-sm-6">
                    <?= $this->formLabel($this->formReportes->get('respon_reporta')) ?>
                    <div class="input-group">
                        <?= $this->formElement($this->formReportes->get('respon_reporta')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-user"></i>
                            </span>
                        </div>
                    </div>
                    </span>
                </div>
            </div>
            <hr>
            <fieldset>
                <legend>Información de la Asignacion</legend>
                <hr>
                <div class="row">

                    <!-- DIRECCIONES -->
                    <div class="col-md-4 mb-3">
                        <fieldset class="border rounded p-3 h-100">

                            <legend class="w-auto px-2 text-primary small">
                                Direcciones Responsables
                            </legend>

                            <ul class="list-group">

                                <?php foreach ($this->direcciones as $direccion): ?>

                                    <input class="form-control" value="<?= $direccion['nombre'] ?>" readonly
                                        title="<?= $direccion['nombre'] ?>">

                                <?php endforeach; ?>

                            </ul>

                        </fieldset>
                    </div>

                    <!-- COORDINACIONES -->
                    <div class="col-md-4 mb-3">
                        <fieldset class="border rounded p-3 h-100">

                            <legend class="w-auto px-2 text-primary small">
                                Coordinaciones Responsables
                            </legend>

                            <ul class="list-group">

                                <?php foreach ($this->coordinaciones as $coordinacion): ?>

                                    <input class="form-control" value="<?= $coordinacion['Coordinacion'] ?>" readonly
                                        title="<?= $coordinacion['Coordinacion'] ?>">


                                <?php endforeach; ?>

                            </ul>

                        </fieldset>
                    </div>

                    <!-- RESPONSABLES -->
                    <div class="col-md-4 mb-3">
                        <fieldset class="border rounded p-3 h-100">

                            <legend class="w-auto px-2 text-primary small">
                                Correos Responsables
                            </legend>

                            <ul class="list-group">

                                <?php foreach ($this->responsables as $responsable): ?>

                                    <input class="form-control" value="<?= $responsable['correo'] ?>" readonly
                                        title="<?= $responsable['correo'] ?>">


                                <?php endforeach; ?>

                            </ul>

                        </fieldset>
                    </div>

                </div>
            </fieldset>
            <hr>
        </fieldset>
        <fieldset>
            <legend>Información de lo repotardo</legend>
            <hr>
            <div class="table-responsive" style="font-size: 11px">
                <table id="tabla" class="table table-striped table-bordered table-hover table-sm" style="width: 150%">
                    <thead class="thead-dark">
                        <tr>
                            <th scope="col" class="text-center align-middle" style="width: 3%">ID</th>
                            <th scope="col" class="text-center align-middle">MES</th>
                            <th scope="col" class="text-center align-middle">FECHA DE CORTE</th>
                            <th scope="col" class="text-center align-middle">FECHA DE SOLICITUD</th>
                            <th scope="col" class="text-center align-middle">FECHA LIMITE</th>
                            <th scope="col" class="text-center align-middle">ESTADO</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php
                        foreach ($this->programacionReporte as $programacion) {
                            echo '<tr>';
                            echo '<td class="text-center" scope="row">' . $programacion['idProgramacion'] . '</td>';
                            /*  echo '<td class="text-center align-middle">';
                             echo '&nbsp;&nbsp;<a href="javascript:verDetalleResultado(' . $resultado['id_resultado'] . ')" title="VER DETALLE DE ESTE RESULTADO"><i class="fas fa-eye"></i></a>';
                             // Se incluye 'En proceso' para que aparezcan las opciones correctamente
                             if ($indicador['estado'] == 'Registrado') {
                                 echo '&nbsp;&nbsp;<a href="javascript:verEditarIndicador(' . $indicador['id_indicador'] . ')" title="ACTUALIZAR ESTE INDICADOR"><i class="fas fa-edit"></i></a>';
                                 echo '&nbsp;&nbsp;<a href="javascript:verEliminarIndicador(' . $indicador['id_indicador'] . ')" title="ELIMINAR ESTE INDICADOR"><i style="color:red" class="fas fa-times-circle"></i></a>';
                             }
                             echo '</td>'; */
                            echo '<td class="text-center align-middle font-weight-bold">' . $programacion['mes'] . '</td>';
                            echo '<td class="text-center align-middle">' . ($programacion['fecha_corte'] ?? 'N/A') . '</td>';
                            echo '<td class="text-center align-middle">' . ($programacion['fecha_solicitud'] ?? 'N/A') . '</td>';
                            echo '<td class="text-center align-middle">' . ($programacion['fecha_limite'] ?? 'N/A') . '</td>';
                            echo '<td class="text-center align-middle">' . ($programacion['estado'] ?? 'N/A') . '</td>';
                            echo '</tr>';
                        }
                        ?>
                    </tbody>
                    <tfoot></tfoot>
                </table>
            </div>
            <fieldset>
                <legend>Información de Trazabilidad</legend>
                <hr>
                <div class="form-row">
                    <div class="form-group col-md-6 col-sm-12">
                        <?= $this->formLabel($this->formReportes->get('registradopor')) ?>
                        <div class="input-group">
                            <?= $this->formElement($this->formReportes->get('registradopor')) ?>
                            <div class="input-group-append">
                                <span class="input-group-text">
                                    <i class="fas fa-user-plus"></i>
                                </span>
                            </div>
                        </div>
                    </div>
                    <div class="form-group col-md-6 col-sm-12">
                        <?= $this->formLabel($this->formReportes->get('fechahorareg')) ?>
                        <div class="input-group">
                            <?= $this->formElement($this->formReportes->get('fechahorareg')) ?>
                            <div class="input-group-append">
                                <span class="input-group-text">
                                    <i class="far fa-calendar-alt"></i>
                                </span>
                            </div>
                        </div>
                    </div>
                    <div class="form-group col-md-6 col-sm-12">
                        <?= $this->formLabel($this->formReportes->get('modificadopor')) ?>
                        <div class="input-group">
                            <?= $this->formElement($this->formReportes->get('modificadopor')) ?>
                            <div class="input-group-append">
                                <span class="input-group-text">
                                    <i class="fas fa-user-edit"></i>
                                </span>
                            </div>
                        </div>
                    </div>
                    <div class="form-group col-md-6 col-sm-12">
                        <?= $this->formLabel($this->formReportes->get('fechahoramod')) ?>
                        <div class="input-group">
                            <?= $this->formElement($this->formReportes->get('fechahoramod')) ?>
                            <div class="input-group-append">
                                <span class="input-group-text">
                                    <i class="far fa-clock"></i>
                                </span>
                            </div>
                        </div>
                    </div>
                    <div class="form-group col-md-6 col-sm-12">
                        <?= $this->formLabel($this->formReportes->get('estado')) ?>
                        <div class="input-group">
                            <?= $this->formElement($this->formReportes->get('estado')) ?>
                            <div class="input-group-append">
                                <span class="input-group-text">
                                    <i class="far fa-clock"></i>
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
            </fieldset>
    </div>
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-danger" data-dismiss="modal"><i class="far fa-times-circle"></i>
        Cerrar</button>
</div>