<?php
$this->formRecursosRbac->prepare();
echo $this->form()->openTag($this->formRecursosRbac);
?>
<div class="modal-body ui-front" style="max-height: 450px; overflow-y: auto;">
    <div class="container-fluid">
        <fieldset>
            <legend>Informacion del Usuario </legend> <hr>
            <div class="form-row">
                <div class="form-group col-md-3 col-sm-3">
                    <?= $this->formLabel($this->formRecursosRbac->get('idRecurso')) ?>
                    <div class="input-group" >  
                        <?= $this->formElement($this->formRecursosRbac->get('idRecurso')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-user"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-9 col-sm-9">
                    <?= $this->formLabel($this->formRecursosRbac->get('metodo')) ?>
                    <div class="input-group" >  
                        <?= $this->formElement($this->formRecursosRbac->get('metodo')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-user"></i>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-12 col-sm-12">
                    <?= $this->formLabel($this->formRecursosRbac->get('recurso')) ?>
                    <div class="input-group" >  
                        <?= $this->formElement($this->formRecursosRbac->get('recurso')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-user"></i>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </fieldset>
    </div>
</div>
<div class="modal-footer">
    <button type="submit" class="btn btn-warning" title="ELIMINAR RECURSO RBAC" ><i style="color: red" class="fas fa-times-circle"></i> Eliminar Recurso Rbac</button>
    <button type="button" class="btn btn-danger" data-dismiss="modal"><i class="far fa-times-circle"></i> Cerrar</button>
</div>
<?= $this->form()->closeTag(); ?>