<?php

$this->formAvanceHistoria->prepare();

$this->formAvanceHistoria->setAttribute('action', $this->url('indicadores/avances', ['action' => 'editar']));

echo $this->form()->openTag($this->formAvanceHistoria);
?>

<div class="modal-body ui-front" style="max-height: 450px; overflow-y: auto;">
    <div class="container-fluid">
        <fieldset>
            <legend>Editar Avance</legend><hr>
            
          
            <?= $this->formElement($this->formAvanceHistoria->get('idAvance')) ?>
            <?= $this->formElement($this->formAvanceHistoria->get('idHistoria')) ?>
            
            <div style="display:none;">
                <?= $this->formElement($this->formAvanceHistoria->get('registradopor')) ?>
                <?= $this->formElement($this->formAvanceHistoria->get('fechahorareg')) ?>
            </div>

          
            <div class="form-row">
                <div class="form-group col-md-12 col-sm-12">
                    <?= $this->formLabel($this->formAvanceHistoria->get('descripcion')) ?>
                    <div class="input-group">
                        <?= $this->formElement($this->formAvanceHistoria->get('descripcion')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-file-alt"></i>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </fieldset>
    </div>
</div>

<div class="modal-footer">
    <button type="submit" class="btn btn-primary" title="GUARDAR CAMBIOS">
        <i class="fas fa-save"></i> Guardar Cambios
    </button>
    <button type="button" class="btn btn-secondary" data-dismiss="modal">
        <i class="far fa-times-circle"></i> Cancelar
    </button>
</div>

<?= $this->form()->closeTag(); ?>

<script>
    
    $("input").keydown(function (e) {
        if (e.which === 13) {
            event.preventDefault();
            return false;
        }
    });
</script>
