<div class="modal-body">
    <div class="container-fluid">
        <div class="alert alert-danger" role="alert">
            <?= $this->msgError ?> - <b>[<?= $this->codigoError ?>]</b>
        </div>
        <p class="text-muted">
            Por favor actualice la pagina e intente de nuevo. <br>
            Si el inconveniente persiste comuniquese con el Administrador
        </p>
    </div>
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-danger" data-dismiss="modal"><i class="far fa-times-circle"></i> Cerrar</button>
</div>
