<?php

$this->formProgramacion->prepare();


$this->formProgramacion->setAttribute('action', $this->url('reportes/programacion', ['action' => 'informacion', 'query' => ['idProgramacion' => $this->idProgramacion]]));

echo $this->form()->openTag($this->formProgramacion);
?>
<div class="modal-body ui-front" style="max-height: 450px; overflow-y: auto;">
    <div class="container-fluid">
        <fieldset>
            <legend>Información del Reporte</legend>
            <hr>
            <?= $this->formElement($this->formProgramacion->get('idProgramacion')) ?>
            <?= $this->formElement($this->formProgramacion->get('idReporte')) ?>
            <div class="form-row">
                <div class="form-group col-md-4">
                    <?= $this->formLabel($this->formProgramacion->get('mes')) ?>
                    <div class="input-group">
                        <?= $this->formElement($this->formProgramacion->get('mes')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-calendar"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-4">
                    <?= $this->formLabel($this->formProgramacion->get('fecha_corte')) ?>
                    <div class="input-group">
                        <?= $this->formElement($this->formProgramacion->get('fecha_corte')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-calendar-alt"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-4">
                    <?= $this->formLabel($this->formProgramacion->get('fecha_solicitud')) ?>
                    <div class="input-group">
                        <?= $this->formElement($this->formProgramacion->get('fecha_solicitud')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-calendar-alt"></i>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-4">
                    <?= $this->formLabel($this->formProgramacion->get('fecha_limite')) ?>
                    <div class="input-group">
                        <?= $this->formElement($this->formProgramacion->get('fecha_limite')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-calendar-alt"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-4">
                    <?= $this->formLabel($this->formProgramacion->get('dia_semana')) ?>
                    <div class="input-group">
                        <?= $this->formElement($this->formProgramacion->get('dia_semana')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-calendar-day"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-4">
                    <?= $this->formLabel($this->formProgramacion->get('semana_mes')) ?>
                    <div class="input-group">
                        <?= $this->formElement($this->formProgramacion->get('semana_mes')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-calendar-week"></i>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </fieldset>
        <hr>
        <fieldset>
            <legend>Información de Trazabilidad</legend>
            <hr>
            <div class="form-row">
                <div class="form-group col-md-6 col-sm-12">
                    <?= $this->formLabel($this->formProgramacion->get('estado')) ?>
                    <div class="input-group">
                        <?= $this->formElement($this->formProgramacion->get('estado')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-info"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-6 col-sm-12">
                    <?= $this->formLabel($this->formProgramacion->get('respon_reporta')) ?>
                    <div class="input-group">
                        <?= $this->formElement($this->formProgramacion->get('respon_reporta')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="far fa-user"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <!--   <div class="form-group col-md-6 col-sm-12">
                    < ?= $this->formLabel($this->formProgramacion->get('estado')) ?>
                    <div class="input-group">
                        < ?= $this->formElement($this->formProgramacion->get('estado')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="far fa-clock"></i>
                            </span>
                        </div>
                    </div>
                </div> -->
            </div>
        </fieldset>
    </div>
</div>
<div class="modal-footer">
    <button type="submit" class="btn btn-success" title="RECIBIR INFORMACIÓN">
        <i class="fas fa-hand-holding"></i> Confirmar Recibido
    </button>
    <button type="button" class="btn btn-danger" data-dismiss="modal">
        <i class="far fa-times-circle"></i> Cancelar
    </button>
</div>

<?= $this->form()->closeTag(); ?>

<script>

    $("input").keydown(function (e) {
        if (e.which === 13) {
            event.preventDefault();
            return false;
        }
    });
</script>