<div style="font-size: 11px" class="table-responsive">
    <table id="tblCobros" class="table table-striped table-bordered table-hover table-sm hover" style="width: 100%">
        <thead class="thead-dark">
            <tr>
                <th scope="col" class="text-center align-middle" style="width: 3%">ID</th>
                <th scope="col" class="text-center align-middle">RECURSO</th>
                <th scope="col" class="text-center align-middle">MÉTODO</th>
            </tr>
        </thead>
        <tbody>
            <?php
            if (count($this->recursosrol) > 0) {
                foreach ($this->recursosrol as $recurso) {
                    echo '<tr>';
                    echo '<th scope="row" class="text-center align-middle">' . $recurso['idRecurso'] . '</th>';
                    echo '<td class="text-center align-middle">' . $recurso['recurso'] . '</td>';
                    echo '<td class="text-center align-middle">' . $recurso['metodo'] . '</td>';
                    echo '</tr>';
                }
            } else {
                echo '<tr>';
                echo '<td colspan="4" class="text-center align-middle font-weight-bold text-danger">';
                echo 'NO SE ENCONTRARON RECURSOS PARA ESTE ROL</td>';
                echo '</tr>';
            }
            ?>
        </tbody>
    </table>
</div>

