<?php
//--------- CARGAR MENSAJES DE ALERTA ------------------------------------------
$flash = $this->flashMessenger();
$notificaciones = [
    'success' => array_merge($flash->getSuccessMessages(), $flash->getCurrentSuccessMessages()),
    'error' => array_merge($flash->getErrorMessages(), $flash->getCurrentErrorMessages()),
    'alert' => array_merge($flash->getMessages(), $flash->getCurrentMessages()),
    'information' => array_merge($flash->getInfoMessages(), $flash->getCurrentInfoMessages()),
    'warning' => array_merge($flash->getWarningMessages(), $flash->getCurrentWarningMessages()),
];
$flash->clearCurrentMessages('default');
$flash->clearCurrentMessages('info');
$flash->clearCurrentMessages('success');
$flash->clearCurrentMessages('warning');
$flash->clearCurrentMessages('error');
$mostrarMensajes = '';
foreach (array_filter($notificaciones) as $tipo => $mensajes) {
    $tipoToastr = 'info';
    $titulo = 'Josandro';
    switch ($tipo) {
        case 'success':
            $titulo = ' OK ';
            $tipoToastr = 'success';
            break;
        case 'error':
            $titulo = ' ERROR ';
            $tipoToastr = 'error';
            break;
        case 'alert':
            $titulo = ' ALERTA ';
            $tipoToastr = 'warning';
            break;
        case 'information':
            $titulo = ' INFORMACION ';
            $tipoToastr = 'info';
            break;
        case 'warning':
            $titulo = ' PRECAUCION ';
            $tipoToastr = 'warning';
            break;
    }
    foreach ($mensajes as $mensaje) {
        $mostrarMensajes .= "toastr.$tipoToastr('$mensaje', '$titulo', {
                closeButton: true,
                debug: false,
                newestOnTop: false,
                progressBar: true,
                positionClass: 'toast-top-full-width',
                preventDuplicates: true,
                onclick: null,
                showDuration: '300',
                hideDuration: '1000',
                timeOut: '10000',
                extendedTimeOut: '10000',
                showEasing: 'swing',
                hideEasing: 'linear',
                showMethod: 'fadeIn',
                hideMethod: 'fadeOut'
            }); ";
    }
}
//------------------------------------------------------------------------------

$title = 'Legalizacion de Contratos Hogar';
$this->headTitle($title);
$this->headScript()->prependScript('
            $(document).ajaxStop($.unblockUI);
            $(document).ready(function() {
                $("#tabla").DataTable({
                    responsive: false,
                    iDisplayLength: 25,
                    sPaginationType: "full_numbers",
                    oLanguage: {
                        sLengthMenu: "Mostrar: _MENU_ registros por pagina",
                        sZeroRecords: "NO SE HA ENCONTRADO INFORMACION",
                        sInfo: "Mostrando <b>_START_</b> a <b>_END_</b> registros <br>TOTAL REGISTROS: <b>_TOTAL_</b> Registros</b>",
                        sInfoEmpty: "Mostrando 0 A 0 registros",
                        sInfoFiltered: "(Filtrados de un total de <b>_MAX_</b> registros)",
                        sLoadingRecords: "CARGANDO...",
                        sProcessing: "EN PROCESO...",
                        sSearch: "Buscar:",
                        sEmptyTable: "NO HAY INFORMACION DISPONIBLE PARA LA TABLA",
                        oPaginate: {
                            sFirst: "<i class=\'fa fa-fast-backward\' aria-hidden=\'true\' title=\'Inicio\'></i>",
                            sPrevious: "<i class=\'fa fa-step-backward\' aria-hidden=\'true\' title=\'Anterior\'></i>",
                            sNext: "<i class=\'fa fa-step-forward\' aria-hidden=\'true\' title=\'Siguiente\'></i>",
                            sLast: "<i class=\'fa fa-fast-forward\' aria-hidden=\'true\' title=\'Fin\'></i>",
                        }
                    },
                    aaSorting: [[0, "desc"]]
                });
                //--------------------------------------------------------------
                // MANIPULACION DEL EVENTO DE CIERRE DEL MODAL
                //--------------------------------------------------------------
                $("#modalFormulario").on("hide.bs.modal", function (e) {
                    Swal.fire({
                        title: "&iquest;DESEA CERRAR EL FORMULARIO?",
                        text: "",
                        icon: "question",
                        showCancelButton: true,
                        confirmButtonText: "Si",
                        cancelButtonText: "No",
                        allowOutsideClick: false
                    }).then((result) => {
                        if (!result.isConfirmed) {
                            $(this).modal("show");
                        }
                    });
                });
                //--------------------------------------------------------------
                ' . $mostrarMensajes . '
            });', 'text/javascript', array('noescape' => true))
        ->prependFile($this->basePath('/js/sistema/recursorbacrol.js'));

//------------------------------------------------------------------------------
?>
<div class="container bg-white rounded-lg shadow-sm p-4 border">
    <h3><i class="fas fa-user-check fa-lg bg-white rounded-lg shadow p-3 text-primary"></i> &nbsp; Roles [<small class="text-primary">Recursos</small>]</h3> <hr>
    <fieldset>
        <h5 class="text-primary">Informacion del Rol</h5> <hr>
        <div class="form-row">
            <div class="form-group col-md-2 col-sm-2">
                <label for="idRol" class="font-weight-bold">ID Rol</label>
                <div class="input-group input-group-sm">
                    <input type="text" id="idRol" name="idRol" value="<?= $this->infoRol['idRol'] ?>" class="form-control font-weight-bold" readonly>
                    <div class="input-group-append">
                        <span class="input-group-text">
                            <i class="fas fa-key"></i>
                        </span>
                    </div>
                </div>
            </div>
            <div class="form-group col-md-8 col-sm-8">
                <label for="rol" >Rol</label>
                <div class="input-group input-group-sm">
                    <input type="text" id="rol" name="rol" value="<?= $this->infoRol['rol'] ?>" class="form-control font-weight-bold" readonly>
                    <div class="input-group-append">
                        <span class="input-group-text">
                            <i class="fas fa-address-card"></i>
                        </span>
                    </div>
                </div>
            </div>
            <div class="form-group col-md-2 col-sm-2">
                <label for="estado">Estado</label>
                <div class="input-group input-group-sm">
                    <input type="text" id="estado" name="estado" value="<?= $this->infoRol['estado'] ?>" class="form-control font-weight-bold" readonly>
                    <div class="input-group-append">
                        <span class="input-group-text">
                            <i class="fas fa-address-card"></i>
                        </span>
                    </div>
                </div>
            </div>
        </div> 
    </fieldset> <hr>
    <button type="button" onclick="location.href = '../roles/index'" class="btn btn-warning" title="REGRESAR A LA SECCION DE ROLES"><i class="fas fa-chevron-left"></i> Regresar</button>
    <button type="button" onclick="verRegistrar(<?= $this->infoRol['idRol'] ?>)" class="btn btn-success" title="VINCULAR RECURSO"><i class="fas fa-plus-circle"></i> Vincular Recurso</button>
    <button type="button" onclick="verImportar(<?= $this->infoRol['idRol'] ?>)" class="btn btn-primary" title="IMPORTAR RECURSOS"><i class="fas fa-download"></i> Importar Recursos</button>
</div><br>
<div class="container">
    <div class="row border rounded-lg shadow-sm p-3">
        <div class="table-responsive" style="font-size: 11px">
            <h5 class="text-primary">Recursos Vinculados</h5> <hr>
            <table id="tabla" class="table table-striped table-bordered table-hover table-sm" style="width: 100%">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col" class="text-center align-middle" style="width: 3%">ID</th>
                        <th scope="col" class="text-center align-middle" style="width: 10%"><i class="fas fa-cog fa-spin"></i></th>
                        <th scope="col" class="text-center align-middle">RECURSO</th>
                        <th scope="col" class="text-center align-middle">METODO</th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                    foreach ($this->recursos as $recurso) {
                        echo '<tr>';
                        echo '<th scope="row" class="text-center align-middle">' . $recurso['idRecurso'] . '</th>';
                        echo '<td class="text-center align-middle">';
                        echo '<a href="javascript:verDetalle(' . $recurso['idRecurso'] . ',' . $recurso['idRol'] . ')" title="VER DETALLE DE ESTE DOCUMENTO"><i class="fas fa-eye"></i></a>';
                        echo '&nbsp;&nbsp;&nbsp;<a href="javascript:verEliminar(' . $recurso['idRecurso'] . ',' . $recurso['idRol'] . ')" title="ELIMINACION DE ESTE DOCUMENTO"><i class="fas fa-times-circle" style="color: red"></i></a>';
                        echo '</td>';
                        echo '<td class="text-center align-middle">' . $recurso['recurso'] . '</td>';
                        echo '<td class="text-center align-middle">' . $recurso['metodo'] . '</td>';
                        echo '</tr>';
                    }
                    ?>
                </tbody>
                <tfoot></tfoot>
            </table>
        </div>
    </div>
</div>

<div id="msgBloqueo" style="display: none;">
    SU SOLICITUD ESTA SIENDO PROCESADA, POR FAVOR ESPERE...
</div>

<div class="modal fade" id="modalFormulario" data-backdrop="static" tabindex="-1" aria-labelledby="lbModalFormulario" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header bg-info text-light">
                <h5 class="modal-title" id="lbModalFormulario">Formulario</h5>
                <button type="button" class="close text-light" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div id="divContenido"></div>
        </div>
    </div>
</div>
<div class="modal fade" id="modalFormularioAux" data-backdrop="static" tabindex="-1" aria-labelledby="lbModalFormularioAux" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="lbModalFormularioAux">Formulario</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div id="divContenidoAux"></div>
        </div>
    </div>
</div>