<?php
//--------- CARGAR MENSAJES DE ALERTA ------------------------------------------
$flash = $this->flashMessenger();
$notificaciones = [
    'success' => array_merge($flash->getSuccessMessages(), $flash->getCurrentSuccessMessages()),
    'error' => array_merge($flash->getErrorMessages(), $flash->getCurrentErrorMessages()),
    'alert' => array_merge($flash->getMessages(), $flash->getCurrentMessages()),
    'information' => array_merge($flash->getInfoMessages(), $flash->getCurrentInfoMessages()),
    'warning' => array_merge($flash->getWarningMessages(), $flash->getCurrentWarningMessages()),
];
$flash->clearCurrentMessages('default');
$flash->clearCurrentMessages('info');
$flash->clearCurrentMessages('success');
$flash->clearCurrentMessages('warning');
$flash->clearCurrentMessages('error');
$mostrarMensajes = '';
foreach (array_filter($notificaciones) as $tipo => $mensajes) {
    $tipoToastr = 'info';
    $titulo = 'Josandro';
    switch ($tipo) {
        case 'success':
            $titulo = ' OK ';
            $tipoToastr = 'success';
            break;
        case 'error':
            $titulo = ' ERROR ';
            $tipoToastr = 'error';
            break;
        case 'alert':
            $titulo = ' ALERTA ';
            $tipoToastr = 'warning';
            break;
        case 'information':
            $titulo = ' INFORMACION ';
            $tipoToastr = 'info';
            break;
        case 'warning':
            $titulo = ' PRECAUCION ';
            $tipoToastr = 'warning';
            break;
    }
    foreach ($mensajes as $mensaje) {
        $mostrarMensajes .= "toastr.$tipo('$mensaje', '$titulo', {
                closeButton: true,
                debug: false,
                newestOnTop: false,
                progressBar: true,
                positionClass: 'toast-top-right',
                preventDuplicates: true,
                onclick: null,
                showDuration: '300',
                hideDuration: '1000',
                timeOut: '10000',
                extendedTimeOut: '10000',
                showEasing: 'swing',
                hideEasing: 'linear',
                showMethod: 'fadeIn',
                hideMethod: 'fadeOut'
            }); ";
    }
}

//------------------------------------------------------------------------------

$title = 'Recursos RBAC';
$this->headTitle($title);
$this->headLink()->prependStylesheet($this->basePath('/css/select2.min.css'));
$this->headScript()->prependScript('
            $(document).ajaxStop($.unblockUI);
            $(document).ready(function() {
                $("#tabla").DataTable({
                    responsive: false,
                    iDisplayLength: 25,
                    sPaginationType: "full_numbers",
                    oLanguage: {
                        sLengthMenu: "Mostrar: _MENU_ registros por pagina",
                        sZeroRecords: "NO SE HA ENCONTRADO INFORMACION",
                        sInfo: "Mostrando <b>_START_</b> a <b>_END_</b> registros <br>TOTAL REGISTROS: <b>_TOTAL_</b> Registros</b>",
                        sInfoEmpty: "Mostrando 0 A 0 registros",
                        sInfoFiltered: "(Filtrados de un total de <b>_MAX_</b> registros)",
                        sLoadingRecords: "CARGANDO...",
                        sProcessing: "EN PROCESO...",
                        sSearch: "Buscar:",
                        sEmptyTable: "NO HAY INFORMACION DISPONIBLE PARA LA TABLA",
                        oPaginate: {
                            sFirst: "<i class=\'fa fa-fast-backward\' aria-hidden=\'true\' title=\'Inicio\'></i>",
                            sPrevious: "<i class=\'fa fa-step-backward\' aria-hidden=\'true\' title=\'Anterior\'></i>",
                            sNext: "<i class=\'fa fa-step-forward\' aria-hidden=\'true\' title=\'Siguiente\'></i>",
                            sLast: "<i class=\'fa fa-fast-forward\' aria-hidden=\'true\' title=\'Fin\'></i>",
                        }
                    },
                    aaSorting: [[0, "desc"]]
                });
                //------------------------------------------------------------------------------
                // MANIPULACION DEL EVENTO DE CIERRE DEL MODAL
                //------------------------------------------------------------------------------
                $("#modalFormulario").on("hide.bs.modal", function (e) {
                    Swal.fire({
                        title: "&iquest;DESEA CERRAR EL FORMULARIO?",
                        text: "",
                        icon: "question",
                        showCancelButton: true,
                        confirmButtonText: "Si",
                        cancelButtonText: "No",
                        allowOutsideClick: false
                    }).then((result) => {
                        if (!result.isConfirmed) {
                            $(this).modal("show");
                        }
                    });
                });
                //------------------------------------------------------------------------------
                ' . $mostrarMensajes . '
            });', 'text/javascript', array('noescape' => true))
        ->prependFile($this->basePath('/js/sistema/recursosRbac.js'))
        ->prependFile($this->basePath('/js/jquery.filterizr.min.js'))
        ->prependFile($this->basePath('/js/select2.min.js'));
?>
<div class="jumbotron">
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-sm-8">
                <h1 class="display-5">Recursos <small>RBAC</small></h1>
                <p>En esta seccion usted puede gestionar todo lo relacionado con los <b>Recursos RBAC</b></p>
                <button type="button" onclick="verRegistrar()" class="btn btn-success" title="REGISTRAR UN NUEVO RECURSO"><i class="fas fa-plus-circle"></i> Registrar Recurso RBAC</button>
            </div>
            <div class="col-md-4 col-sm-4 text-center d-none d-sm-block">
                <img src="<?= $this->basePath('img/recursosrbac.png'); ?>" class="rounded img-fluid" alt="Imagen" style="width: 60%; height: auto">
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="table-responsive" style="font-size: 11px">
            <table id="tabla" class="table table-striped table-bordered table-hover table-sm">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col" class="text-center align-middle">ID RECURSO</th>
                        <th scope="col" class="text-center align-middle" style="width: 10%"><i class="fas fa-cog fa-spin"></i></th>
                        <th scope="col" class="text-center align-middle">RECURSO RBAC</th>
                        <th scope="col" class="text-center align-middle">METODO</th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                    foreach ($this->recursos as $recurso) {
                        echo '<tr>';
                        echo '<th scope="row" class="text-center align-middle">' . $recurso['idRecurso'] . '</th>';
                        echo '<td class="align-middle">';
                        echo '<a href="javascript:verDetalle(' . $recurso['idRecurso'] . ')" title="VER DETALLE DE ESTE RECURSO"><i class="fas fa-eye"></i></a>';
                        echo '&nbsp;&nbsp;&nbsp;<a href="javascript:verEditar(' . $recurso['idRecurso'] . ')" title="ACTUALIZAR LA INFORMACION DE ESTE RECURSO"><i class="fas fa-edit"></i></a>';
                        echo '&nbsp;&nbsp;&nbsp;<a href="javascript:verEliminar(' . $recurso['idRecurso'] . ')" title="ELIMINAR ESTE RECURSO"><i style="color: red" class="fas fa-times-circle"></i></a>';
                        echo '</td>';
                        echo '<td class="text-center align-middle">' . $recurso['recurso'] . '</td>';
                        echo '<td class="text-center align-middle">' . $recurso['metodo'] . '</td>';
                        echo '</tr>';
                    }
                    ?>
                </tbody>
                <tfoot></tfoot>
            </table>
        </div>
    </div>
</div>

<div id="msgBloqueo" style="display: none;">
    SU SOLICITUD ESTA SIENDO PROCESADA, POR FAVOR ESPERE...
</div>

<div class="modal fade" id="modalFormulario" data-backdrop="static" tabindex="-1" aria-labelledby="lbModalFormulario" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header bg-info text-light">
                <h5 class="modal-title" id="lbModalFormulario">Formulario</h5>
                <button type="button" class="close text-light" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div id="divContenido"></div>
        </div>
    </div>
</div>
