<?php
$form->prepare();
echo $this->form()->openTag($form);
?>
<div class="modal-body ui-front">
    <div style="padding: 10px" class="container-fluid text-center">        
        <fieldset>
            <legend>Informacion del Recurso RBAC</legend>
            <hr>
            <div class="form-row">
                <div class="form-group col-md-8 col-sm-12">
                    <?= $this->formLabel($form->get('recurso')) ?>
                    <div class="input-group">  
                        <?= $this->formElement($form->get('recurso')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fa fa-folder-open"></i>
                            </span>
                        </div>
                    </div>
                </div>                
                <div class="form-group col-md-4 col-sm-12">
                    <?= $this->formLabel($form->get('metodo')) ?>
                    <div class="input-group">
                        <?= $this->formElement($form->get('metodo')) ?>
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fa fa-check-square"></i>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </fieldset>                    
    </div>
</div>
<div class="modal-footer" id="footerFormularioReg" style=" padding: 20px">
    <button type="submit" class="btn btn-success" title="REGISTRAR RECURSO RBAC"><i class="fas fa-save"></i> Registrar Recurso RBAC</button>
    <button type="button" class="btn btn-danger" data-dismiss="modal"><i class="fas fa-times"></i> Cerrar</button>
</div>
<?= $this->form()->closeTag(); ?>
